### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by mxstbr** [styled-components/polished#10]
We need a better name.

While the meaning of the word `cynosure` is amazing, two hours after I first found the name I couldn't even remember it – not a good sign.

Any ideas?

`pedicure` isn't taken on npm yet, would fit with our whole 💅-thing and has something to do with styling, but it does have a slightly dirty connotation maybe? `import { clearfix } from 'pedicure'`

/cc @styled-components/design @styled-components/cynosure

**Comment by okonet** [comment]
What about something with `styled-` prefix?

styled-lib
styled-toolbox 
styled-helpers

Not super cool but could serve the purpose better and has a strong cannotation with styled-components.

**Comment by mxstbr** [comment]
No, this library isn't styled-components specific at all, that's kind of the point. 😊

We'll get other css-in-js method authors involved as soon as we have a good repo setup and name, but essentially nothing in this library has to be styled-components specific. We are building all these amazing helpers everybody needs, so let's get everybody involved!

**Comment by okonet** [comment]
I've just checked the Latin name for the small 🐻 and it's called „Ursa minor“. What if we just take the Ursa part?

`import { clearfix } from "ursa"`

**Comment by mxstbr** [comment]
Already taken on npm :confused:

**Comment by ericclemmons** [comment]
I recommended "polish" (since :nailcare: is the emoji) or some variation on the original repo.

**Comment by cdonohue** [comment]
Looks like `polish` is taken on `npm`. Maybe prefix it like `style-polish`?

**Comment by geelen** [comment]
`polished` isn't taken. It's a much subtler connection to `styled-components` in that it's just the past tense that ties them together. Also, it doesn't clash with 🇵🇱 

I vote `polished`

```js
import styled from 'styled-components'
import { clearfix } from 'polished'
```

LGTM 👍

**Comment by cdonohue** [comment]
I like that @geelen! Very nice!

**Comment by mxstbr** [comment]
Lovely! Renaming all the things!

**Comment by okonet** [comment]
LGTM too! Now we only need to find a symbol that represents it 🤔

**Comment by mxstbr** [comment]
Since those helpers will mostly be used within interpolations:

```JS
import { clearfix } from 'polished'

const Button = styled.button`
  ${clearfix()}
`
```

I wouldn't mind reusing 💅, except with interpolation syntax `${}` around it:

`${💅}`

**Comment by ericclemmons** [comment]
How 'bout `✨` for `polished`?

**Comment by mxstbr** [comment]
I love that @ericclemmons!

${✨}

What do you think @okonet?

**Comment by okonet** [comment]
![2016-11-08 at 10 17](https://cloud.githubusercontent.com/assets/11071/20093333/916494dc-a59c-11e6-9ef6-2c08c7c13782.png)

Thoughts?

**Comment by mxstbr** [comment]
I like it! 😍
