### ISSUE TITLE
Should styled-tools be added?

### ISSUE THREAD

**Issue by aaronmcadam** [styled-components/polished#103]
https://github.com/diegohaz/styled-tools is a small library that adds [2 little functions](https://github.com/diegohaz/styled-tools#api) for conditionally adding styles (`prop` and `ifProp`). It might be nice to have something similar in `polished`, though I do wonder whether other style libraries expose `props` as nicely as `styled-components`. Just a thought 😄

**Comment by nikgraf** [comment]
Cool lib, but not sure if it's a good fit. Polished itself is supposed to be a general purpose CSS in JS lib. What do you guys think @mxstbr @bhough?

**Comment by bhough** [comment]
In the interest of keeping this library agnostic, I don't think we should include it. Technically this doesn't even necessarily need to be used with React, so `props` wouldn't exist.

**Comment by aaronmcadam** [comment]
Thanks for the feedback guys, I agree after thinking about it for a while.
