### ISSUE TITLE
[V2] rgba function should behave like Sass rgba function

### ISSUE THREAD

**Issue by tolgaergin** [styled-components/polished#104]
The rgba function that you created expects 
```${rgba(255, 205, 100, 0.7)}``` or 
```${rgba({ red: 255, green: 205, blue: 100, alpha: 0.7 })};``` 
when we use it in styled-components. 

I don't know, my approach might be wrong but If I use your rgba function like ```${rgba('#000', 0.1)}``` in order to get the same css ```rgba(0, 0, 0, 0.1)``` when I use rgba function in [Sass,](https://github.com/sass/node-sass/blob/1f5eaff36a7e06126df0902df681aa980250be55/src/libsass/src/functions.cpp#L267) it would be better.

I use this function to get the result that I mentioned.
```javascript
const hexToRgb = (hex) => {
  // http://stackoverflow.com/a/5624139
  var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
  hex = hex.replace(shorthandRegex, function (m, r, g, b) {
    return r + r + g + g + b + b;
  });

  var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16),
  } : null;
};

const rgba = (hex, alpha) => {
  const color = hexToRgb(hex);
  return `rgba(${color.r}, ${color.g}, ${color.b}, ${alpha})`;
};

export const Header = styled.div `
  box-shadow: 0 0 5px ${rgba('#000', 0.1)};
`;
```

I wonder your ideas about it.

I look forward to use Polished in a real project.
Thanks

**Comment by nikgraf** [comment]
Interesting case. The functionality is already covered by https://polished.js.org/docs/#transparentize

To be honest I'm not sure. I thought this would not be needed, but if this is a very common case for Sass users we might want to consider supporting it.

**Comment by tolgaergin** [comment]
Thanks for your thoughts Nik,

I've been asking many people around me for 2 weeks. the most common built-in functions in sass in my circle like that 1) rgba 2) lighten, darken

Additionally, I've investigate the most [popular front-end libraries](http://cssdb.co/) uses Sass, 
if I compare their usage of rgba(#hex, alpha) or transparentize(alpha, #hex)

| Library | rgba usage | transparentize usage
| --- | --- | --- |
| [Bootstrap](https://github.com/twbs/bootstrap/tree/v4-dev/scss) | >3+ | 0 |
| [Bourbon](https://github.com/thoughtbot/bourbon) | >3+ | 0 |
| [Foundation](https://github.com/zurb/foundation-sites) | >3+  | 0 |
| [Ionic](https://github.com/driftyco/ionic) | >3+ | 0 |
| [Materialize](https://github.com/Dogfalo/materialize) | 0 | 1 |
| [Bulma](https://github.com/jgthms/bulma) | >3+ | 1 |

Personally, I always preferred to use rgba rather than transparentize due to these reason
1) It is simple just 4 letters
2) Easy to write while setting colors #34d instead of rgba(51, 68, 221, 1) 
3) Easy to remember hex codes
4) When collecting colors on Sketch or Photoshop, easy to copy to hex code and give the alpha channel
5) It is the same experience on Sketch or Photoshop like opacity. with Transparentize, you need subtract 1 - opacity (that you see on design application)

**Comment by bhough** [comment]
I do see where this would be useful, what we would need to sort out though is how this jives with what RGBA currently does for us. Would the API become a bit too confusing if it supported both this use case as well as what it currently does?

**Comment by nikgraf** [comment]
@bhough shouldn't be too crazy to do since we can match for the amount of arguments

I'm still be undecided if we want to encourage a simpler API with the explicit function or opt in for this special case …

**Comment by nikgraf** [comment]
@tolgaergin thanks a ton for the research! 🙌

**Comment by bhough** [comment]
@nikgraf agreed, meant more confusing as it seems to be doing two different things using the same method. If that pattern is already established, it may not be too bad to just implement it as opt in, while leaving transparentize in place.

**Comment by nikgraf** [comment]
question is: do we want this now or wait a bit longer until more people ask for it?

**Comment by bhough** [comment]
In the interest of getting a release out soon(ish), I would vote for us to wait. If we lacked a method for doing this it would be different, but with `tranparentize`, at worst it's a minor inconvenience.

**Comment by nikgraf** [comment]
sounds good!

**Comment by nikgraf** [comment]
@bhough Max was thinking about launching at React London. I tried to reach you via private message on Twitter.

**Comment by bassbump** [comment]
Personally I always use rgba like this; rgba(#fff, .5). I think this should be supported.

**Comment by kabulore** [comment]
I hope the polished can support multiple function like ${rgba('#000', 0.1)} or ${rgba('#cbcbcb', 0.1)} or ${rgba(200, 200, 200, 0.1)} or ${rgba(green, 0.1)}. Thank you!

**Comment by bhough** [comment]
@nikgraf @mxstbr I think at this point there is enough demand to warrant implementing this.

**Comment by nikgraf** [comment]
Just left a comment on the PR. We are going to merge this asap.

**Comment by alocke12992** [comment]
@nikgraf , @bhough  Just wanted to say thanks for getting this feature added in! You guys do some great work.  😃👏

**Comment by AdamGulmantowicz** [comment]
Found another issue with rgba and gradient functions.
This cause an error:
`background-image: linear-gradient(to right, ${rgba(#DE6262, .2)}, ${rgba(#FFB88C, .2)});`

Use this instead
`export const linearGradient = string => {
  return `linear-gradient(${string})`
}`

Usage example:
`background-image: ${linearGradient(`to right, ${rgba('#DE6262', .2)}, ${rgba('#FFB88C', .2)}`)};`

I hope someone will find this solution usefull.
