### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by MrLoh** [styled-components/polished#109]
This is just what I was looking for. But I can't install it.

I tried to npm install the package, but only the `clearfix` functionality was installed. I guess the node package is very outdated or something.

**Comment by bhough** [comment]
@MrLoh This has not been officially released yet, so this is expected.

**Comment by JikkuJose** [comment]
Just stumbled on this, it may be better to note this on the homepage.

**Comment by nikgraf** [comment]
We will release soon 😄
