### ISSUE TITLE
homepage example contains syntax error

### ISSUE THREAD

**Issue by rattrayalex** [styled-components/polished#117]
I pasted this into the console on the homepage: 

```
const styles = {
  color: lighten(0.2, '#000'),
  font-size: modularScale(1),
  [hiDPI(1.5)]: {
    font-size: modularScale(1.25)
  }
}
```
And, unsurprisingly, got
```Uncaught SyntaxError: Unexpected token -```

I assume it needs to be `"font-size": `?

**Comment by mxstbr** [comment]
Yes, good call! PR welcome.

**Comment by rattrayalex** [comment]
Sure, forthcoming

**Comment by nikgraf** [comment]
thanks @rattrayalex
