### ISSUE TITLE
homepage svg logo contains font

### ISSUE THREAD

**Issue by Haroenv** [styled-components/polished#122]
The text has `FiraSans-Medium, Fira Sans` as font-family, which causes it to fallback into serif. There are two options to fix this:

1. add `, monospace` to the font
2. convert text into outlines

The first has the advantage of generating a smaller svg, the second will be exactly how you see it on your screen.

**Comment by mxstbr** [comment]
Would love to convert it to outlines, mind submitting a PR to https://github.com/styled-components/brand? Thank you so much!

**Comment by Haroenv** [comment]
styled-components/brand#1
