### ISSUE TITLE
[RFC] Adopt more explicit function arguments

### ISSUE THREAD

**Issue by rtsao** [styled-components/polished#126]
#### Space-delimited arguments

I think the concept of space delimited arguments of css property values often leads to considerable ambiguity. IMHO this is a concept that is ideally avoided when defining styles in JavaScript in favor of explicit arguments. These are really bad when there's several space-delimited values, such as in the `box-shadow` property.

For example:

```css
.shadow {
  box-shadow: 2px 2px 2px 1px red;
}
```

Personally, I have need to look up the meaning of these space delimited arguments **100% of the time.**

With the current pattern adopted by `polished`, the equivalent might helper function might be something like (based on the [`animation` shorthand helper](https://polished.js.org/docs/#animation)):

```js
boxShadow(['2px', '2px', '2px', '1px', 'red']);
```

Instead, I think something like the following would be vastly more clear:

```js
boxShadow({
  offset: {x: '2px', y: '2px'},
  blurRadius: '2px',
  spreadRadius: '2px',
  color: '2px'
});
```

I would **not** need to look up this interface every time. Having more explicit arguments also makes Flow type annotations and IDE autocomplete even nicer.

#### Directional properties

Directional properties are very common. I think it would be nice to give this a consistent, explicit, direct JavaScript API. For example, rather than:

```js
borderWidth('12px', '24px', '36px', '48px');
borderWidth('12px', '24px');
borderWidth('12px', '24px', '8px'); // What does this mean again? I have to think about this.
borderWidth('7px', '7px', '7px', '11px'); // Not so DRY
```

We would have something like:

```js
borderWidth({top: '12px', right: '24px', bottom: '36px', left: '48px'});
borderWidth({x: '24px', x: '12px'});
borderWidth({x: '24px', y: '12px', bottom: '8px'}) // Precedence is obvious
borderWidth({all: '7px', left: '11px'); // More DRY, can use Object.assign as well for overriding
```

I think this is an improvement in terms of expressiveness and ergonomics for the reasons above.

#### Conclusion

I think a "lodash for style objects" library is an opportunity to correct the mistake of implicit parameters in CSS. It's certainly more ambitious than merely mirroring the pattern of space-delimited property values and does result in further abstraction from CSS, but I think it's ultimately better in a world where all styles are defined in JavaScript and all CSS is generated from JavaScript. We can reduce ambiguity and have a really nice style authoring experience with strict object Flow types.

Several months ago I made a library very similar to `polished` where I implemented these things: https://lostyle.js.org/, but I think it would be better to join forces. I think the way it handles `border` shorthands is nice: https://lostyle.js.org/global.html#border and expands on the ideas I've described here.

All this stuff would be a breaking change, but I think ultimately the API is much more clear.

Feel free to close this issue if you don't agree with this opinion. Cheers! 😄

**Comment by mxstbr** [comment]
I could see us merging that in for sure. What do you think @bhough @nikgraf?

**Comment by bhough** [comment]
I would definitely would want to keep the existing api in place given that the original goal was to make these as portable as possible from libraries like bourbon. Though I do believe this is another case (as @nikgraf and I were discussing on #104) where the idea of having multiple APIs for the same mixin has come up, and whether that should be seen as flexible or confusing.

**Comment by guzart** [comment]
I believe the proposed API would be great for a beginner, but I can imagine a more advanced CSS user finding it somewhat verbose.

Maybe the explicit API could be exposed in a subdirectory, similar to [Lodash's FP](https://github.com/lodash/lodash/wiki/FP-Guide), something among the lines of `styled-components/fancy`.

**Comment by nikgraf** [comment]
@rtsao first of all: lostyle looks really cool, good job there 👏

I really like this proposal and usually I'm more in favour of having one way of doing things, but in for the sake of making it easy for most people we followed the approach of accepting different signatures. Mostly inspired by the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle)

> Be conservative in what you do, be liberal in what you accept from others


I'm not too fond of a `polished/fancy` version (yet). Might be a nice idea to test features, but ideally we can keep it simple right now.

I vote for add improving the API while keeping the old signature as well. This can be simply done with dynamic type checks in the beginning of each functions same as we did in `rgb`, `rgba`, `hsl` or `hsla`. See https://github.com/styled-components/polished/blob/master/src/color/rgb.js#L13-L14

**Comment by bhough** [comment]
@nikgraf @mxstbr curious thoughts on including this as part of V2. Are we sold on expanding the apis of existing modules (where appropriate) to allow shorthand and explicit styles?

**Comment by geelen** [comment]
My 2c as someone fairly confident with CSS, I think API quirks like this are better left exposed directly to the consumer, since they're an unavoidable part of the platform. For example, as soon as you need to drop from styling with polished into styling with CSS or have to change an element's style using inline styles, you're straight back to the "native" interface. So it makes your knowledge less portable.

The CSS spec has a huge surface area, not just around value syntax but plenty of properties that seem oddly named or things that only work in pairs, but I've never seen an abstraction over the top that works well enough for long enough that it ends up being a net benefit.

That said, offering an API with both short and long hand args doesn't cost you much and might help folks come back and read their code later, so it might be worth adding, but I wouldn't make it the primary API

**Comment by bhough** [comment]
I believe I have a solution for v2 that will allow us to both support this without causing much overhead as well as make it opt-in on a per module basis with no modifications to the module itself.
