### ISSUE TITLE
Clarify use of object rest spread operator in docs?

### ISSUE THREAD

**Issue by jonasws** [styled-components/polished#128]
First of fall: Awesome library! Really cool to throw this at the guys claiming that they "live and die' by Sass functions!

I have suggestion/comment regarding the docs: The examples make extensive use of the object rest spread operator, which is still a proposal, and you may save a lot of developers some time by indicating that they need to use [babel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread), in order to leverage the new syntax.

Happy to make a PR to the docs if this is indeed something that should be in there!

**Comment by mxstbr** [comment]
I agree, that would be nice to have! Let's add it to the README for now, as #112 is completely reworking the docs.

**Comment by mxstbr** [comment]
Done in #130, thanks @jonasws!
