### ISSUE TITLE
Opacify is not working

### ISSUE THREAD

**Issue by juangl** [styled-components/polished#137]
The following code does this:

```javascript
opacify(0.6, 'rgba(255, 255, 255, 0.8)') // #fff
opacify(0.6, '#fff') // #fff
```

what's wrong?

 I don't understand why `transparentize` works well. Which is the difference between the two.

### Version
  - polished@1.0.2

**Comment by nikgraf** [comment]
Hey, the docs are actually outdated. `opacify` does exactly the opposite of `transparentize`. The one increases the alpha the other reduced it. I just upend a PR with updated docs.

I hope that helps :)

**Comment by juangl** [comment]
That make sense. Thank you.
