### ISSUE TITLE
Integrate JSDoc plugin for parsing working examples from tests

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#14]
We will create a JSDoc plugin that will parse out `@tests` comments to pull working examples from tests and expected output from Jest snapshots. This will be leveraged in our document generation.

**Comment by bhough** [comment]
Addressed by https://github.com/styled-components/polished/pull/15

**Comment by mxstbr** [comment]
Working on this, got the first part ready but this is blocking right now: https://github.com/documentationjs/documentation/issues/630

Will continue work once that's resolved!

**Comment by mxstbr** [comment]
This won't work out, it's sadly too complex at this point. :cry:
