### ISSUE TITLE
Add React Native Helpers For Device Width/Height

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#143]
Opening this to discuss the possibility of adding helpers for React Native percentages based on Height/Width. The API could look something like this:

```javascript 
{
  'font-size': deviceWidth('10%'),
  'height': deviceHeight('100%'),
}
```

which would replace something like this:

```javascript 
{
  'font-size': (Dimensions.get('window').width * .10),
  'height': (Dimensions.get('window').height),
}
```

See: https://facebook.github.io/react-native/docs/dimensions.html

 We could potentially get really fancy and offer the ability to determine values based off measurements other than percentage.

Additional context: https://github.com/styled-components/polished/issues/129#issuecomment-291002816

@mxstbr @nikgraf thoughts on this idea?

**Comment by nikgraf** [comment]
Nice, does it make sense to have a separate package or part of the package dedicated to React Native?

**Comment by bhough** [comment]
That is a good question. In addition to percentage helpers, there is the simple difference of a lot of the FB subset of CSS for React Native being camel-cased instead of hyphenated. There also seem to be some challenges around responsive design in general: https://medium.com/@elieslama/responsive-design-in-react-native-876ea9cd72a8

Seems like there would be 

1. React Native specific helpers (like outlined above).
2. React Native versions of other polished mixins/helpers.

Why React Native is a different beast, my worry with a separate package is in the case of 2, where there would be a lot of duplicated code with just the casing of the properties being different. 

Since we encourage (force) individual pieces to be imported, we could have a stand-alone section for React Native specific mixins/helpers. Then on the ones with shared code we could (theoretically) detect if it is a RN app and adjust the property names automatically, keeping the file size the same with dead code elimination.

**Comment by mxstbr** [comment]
`styled-components` works on ReactNative with standard `polished` (we take care of camel casing etc.), so I'm wary of introducing another package for these. Why not just add them to the package, but make it clear in the docs they're RN only?

**Comment by bhough** [comment]
@mxstbr I think that is the proposition. The only part up in the air was the camel casing, need to research how other libraries that support RN. Hopefully it is handled the same way styled components does it.

**Comment by bhough** [comment]
This has been open for over a year with no real interest.
