### ISSUE TITLE
Add EXAMPLES.md

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#144]
Document examples of using `polished` with various css-in-js solutions. This is the first step towards adding the ability to toggle between examples with these different libraries directly in the docs.

**Comment by yeskunall** [comment]
I am willing to help with this. One question tho: do you want an example for **_each_** method available in the API, or..?

**Comment by bhough** [comment]
@yeskunall Right now we show two examples for our methods: One for usage with general `css-as -js` objects, and one specifically for `styled-components`. I'd like to start collecting more specific examples of using `polished` with other specific libraries, especially where the usage is slightly different. For example how to use it with https://github.com/paypal/glamorous, which allows you to apply styles as props directly: https://github.com/paypal/glamorous#this-solution. Or aphrodite or glamor that requires the use of the `css` method.

**Comment by yeskunall** [comment]
I see. So is the focus to ease the integration of `polished` into already existing libraries that make use of the concept behind `styled-components`? What happens when the number of these libraries grows? Do you guys plan on constantly updating the documentation, in that case? Or do you want to restrict the usage to popular libraries? Just wondering.

**Comment by bhough** [comment]
The goal of `polished` is to be library agnostic. Ideally, it works with any library that has CSS expressed as Objects as it's base (which `styled-components` and many others do). The goal of the docs is to ease the integration where it may not be immediately obvious how to use `polished` with a specific library. We will do our best to continue to update docs for new libraries as they gain in popularity.

**Comment by nikgraf** [comment]
I like the idea. I think in this case we should have a clear ruleset when we include a new solution. Right now there are about 50+ (see https://github.com/MicheleBertoli/css-in-js) and this could eventually lead to slow loading of the Polished page itself.

Which one of these 50+ would you like to add and why at the current state?

**Comment by bhough** [comment]
Closing this in favor of an item in #164.
