### ISSUE TITLE
steps in modularScale() is not calculated correctly

### ISSUE THREAD

**Issue by boxfish** [styled-components/polished#147]
Given default base (`1em`) and ratio (`perfectFourth`), modularScale(2) should return `1.77689em`, but currently it is returning `2.666em`. 

It seems the current output is calculated by `base * ratio * steps`, but it should be `base * Math.pow(ratio, steps)`

**Comment by yeskunall** [comment]
Looks like [this](https://github.com/styled-components/polished/blob/master/src/helpers/modularScale.js#L82) confirms what @boxfish reported. Based on [modularscale.com](http://www.modularscale.com/?1&em&1.333), modular scale is calculated as `base * Math.pow(ratio, steps)`.

**Comment by mxstbr** [comment]
Yes please, PR very welcome!

**Comment by brikou** [comment]
@mxstbr I just made a PR for this one and another bug when steps is 0, can you review please #149 

Thank you for your work :+1:

**Comment by bhough** [comment]
Closed by #149. Thanks @brikou!
