### ISSUE TITLE
Color Luminance utility functions

### ISSUE THREAD

**Issue by souporserious** [styled-components/polished#148]
Would you be interested in adding a luminance helper to this library? I'm using this right now which pulls from the knowledge of other color libraries:

```js
// http://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef
function getLuminance(color) {
  const rgbColor = parseToRgb(color);
  const [r, g, b] = Object.keys(rgbColor).map(key => {
    const channel = rgbColor[key] / 255;
    return channel <= 0.03928
      ? channel / 12.92
      : Math.pow((channel + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
```

ported this from [ChromaJS](https://github.com/gka/chroma.js/blob/d2c6d917df4ba2b87d8a740de116a0656bcbdfd5/src/io/luminance.coffee) because I didn't want to import the whole lib, not sure if you want to put it in here though
```js
const EPS = 1e-7;

function setLuminance(amount, color) {
  const { red, green, blue, alpha = 1 } = parseToRgb(color);
  let rgb;
  if (amount === 0) {
    rgb = rgba(0, 0, 0, alpha);
  } else if (amount === 1) {
    rgb = rgba(255, 255, 255, alpha);
  } else {
    let maxIteration = 20;
    const test = (color1, color2) => {
      const mixed = mix(0.5, color1, color2);
      const mixedLuminance = getLuminance(mixed);
      if (Math.abs(amount - mixedLuminance) < EPS || !maxIteration--) {
        return mixed;
      }
      if (mixedLuminance > amount) {
        return test(color1, mixed);
      }
      return test(mixed, color2);
    };
    rgb = getLuminance(color) > amount
      ? test('#000', color)
      : test(color, '#fff');
  }
  return rgb;
}
```

Could even add some simple `isDark` and `isLight` functions with this addition. I can put together a PR if you are interested, just let me know :)

**Comment by bhough** [comment]
Thanks for the idea @souporserious. I'd definitely be interested in something like this. One thing we are lacking that I've found useful is something similar to color guards in LESS: http://lesscss.org/features/#mixin-guards-feature

Where you can style something based on the lightness/darkness of a color. This seems like something that could get us there.

On the library front, our goal is to not have any dependencies, so the version that doesn't use Chroma would be necessary. Definitely would love to see a PR for this.

**Comment by souporserious** [comment]
Sweet! Those mixins look rad. I'll start a PR for this as soon as I get a chance :)

**Comment by jcquinlan** [comment]
Does the luminosity function only need to accept a hex color value? Or rgb/rgba as well?

**Comment by souporserious** [comment]
Great to see `getLuminance` merged 🎉  any status on a `setLuminance` function? I might be able to squeeze in a PR this week.

**Comment by bhough** [comment]
@souporserious It is on my radar but haven't put any thought or work into yet. Have a few things I want to tackle before that, but would definitely accept a PR for it.
