### ISSUE TITLE
RFC change modularScale default unit from `em` to `rem`

### ISSUE THREAD

**Issue by brikou** [styled-components/polished#150]
`em` units are based on the font size of the element they’re used on whereas `rem` units are based on the font size of the html element.

I suggest to update modularScale signature to use `rem` as default.

read more here https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984

WDYT ?

**Comment by brikou** [comment]
EDIT: in fact I think that default base should be simply 1 (as float). This helper shouldn't have anything to do with unit IMO.

**Comment by brikou** [comment]
The more I think about it... the more I feel that I am wrong and `1em` as base unit is perfect... So closing this issue

**Comment by brunnolou** [comment]
@brikou can you explain why you now think `em` is better instead of `rem` in modular scale?

IMHO `modularScale(2)` should always be the same `px` size, and not be determined by the font size of the parent.
