### ISSUE TITLE
Improvement proposal for calculation

### ISSUE THREAD

**Issue by sapottier** [styled-components/polished#156]
Hello,

First of all, sorry for my english. Unless I am mistaken, there is no calculation tool ? Currently, I have to write something like :

```
`
top: ${parseFloat(theme.header.height) // or stripUnit
	+ parseFloat(theme.spacing.sm) * 4
	+ parseFloat(theme.content.tab.height)
	+ parseFloat(theme.content.header.height)}rem;
`
```
pretty ugly…

maybe something like : 

```
`
top: ${calc(theme.header.height
	+ theme.spacing.sm * 4
	+ theme.content.tab.height
	+ theme.content.header.height, 'rem')};
`
```
Also, this can be converted with babel-plugin-polished and disregard the units.

Thank you,

Simon

**Comment by bhough** [comment]
@sapottier Are you looking for a replacement for regular CSS Calc? Support for that is pretty robust at this point: http://caniuse.com/#feat=calc

**Comment by sapottier** [comment]
@bhough I use calc to mix fixed dimension and %. For nested calculation there is some trouble (often with IE…). Also, considering the result as constant, leting babel-plugin-polished compiled the result seems to be a good thing ?

**Comment by nikgraf** [comment]
@sapottier what do you think about adding this to a micro-library that we mention in the readme as an extension to polished?

**Comment by sapottier** [comment]
I will do it in this way. First step, find the best approach: just eval or function constructor _(not secure if we bypass compilation), tagged template, shunting-yard, reverse polish notation, …

I will investigate.

**Comment by bhough** [comment]
Going to close this, but please submit a PR to add the micro-library to the readme when available.
