### ISSUE TITLE
`array.includes` is not transpiled and breaks all IE + Edge 13

### ISSUE THREAD

**Issue by feyzo** [styled-components/polished#158]
`polished` version: 1.0.4

What i am seeing:

Transpiled `node_modules/polished/lib/shorthands/position.js` Line 65-66

```
...
  if (positionMap.includes(positionKeyword)) {
    return _extends({
...
```

Solutions:
1. Replace `includes` with `indexOf(...) >= 0`
2. Use babel but see `pitfalls` https://www.npmjs.com/package/babel-plugin-array-includes

Reproduction:

Search for `.includes`
https://github.com/styled-components/polished/search?utf8=%E2%9C%93&q=.includes&type=

**Comment by feyzo** [comment]
I can create a PR if you agree to go with solution 1

**Comment by nikgraf** [comment]
@feyzo your first solution sounds good

**Comment by bhough** [comment]
A note that this will impact `position`, `textInputs`, and `buttons`.
