### ISSUE TITLE
[V2] Camel Case Object Keys

### ISSUE THREAD

**Issue by dlwalsh** [styled-components/polished#167]
I'd like for there to be a way to get the style object with the keys in camel case, as opposed to the default kebab case.

For instance, glamorous complains about `border-left-width` when it expects `borderLeftWidth`. Glamorous is still smart enough to correctly interpret the style, but it would be nice to do away with the console warning.

I'd be happy to submit a PR for such a change, but I'm unsure of the best way to go about it. I suggest an alternative import point, e.g.

```
import { borderWidth } from 'polished/camelCase'
```

Thoughts?

**Comment by bhough** [comment]
Thank you for the proposal @dlwalsh. This has come up before in the context of styles for [React Native](https://github.com/styled-components/polished/issues/143#issuecomment-293164086), and generally we have been hesitant to add that functionality directly to polished as most libraries either don't expect the camelCased properties or when they do, they take care of the conversion within the library (such as `styled-components` with React Native). 

@kentcdodds would love to know your thought process behind the warning (but fixing) in `glamorous`. Is the intent to eventually remove the conversion to camelCase? I'd imagine that it still needs to be converted back to generate valid CSS when provided in camelCase?

**Comment by kentcdodds** [comment]
That warning's coming from glamor (cc @threepointone) and I think that there definitely should be an API to allow for camelCase considering the React `style` prop also expects camelCase.

**Comment by bhough** [comment]
Thanks @kentcdodds. I will do some further research here. Probably will need to put a table together on which approach the popular implementations prefer/support as a starting point.

**Comment by kentcdodds** [comment]
I've yet to see a CSS-in-JS solution that didn't use camel case for property keys if it users objects.

**Comment by nikgraf** [comment]
Makes sense to me to support it. I dislike the idea of importing from `'polished/camelCase'`. To me this feels like it's not a first class citizen while it should be.

What are our options?
- Two different libraries generated from one source code with two dedicated docs pages.
- Import from a subdirectory 'polished/camelCase'
- An argument in every function which it's relevant
- A global setting for all polished functions
- Any other ideas?

**Comment by kentcdodds** [comment]
Well, it appears that the original/primary use-case for polished was to be used with styled-components. With that in mind, it seems reasonable for the camelCase use case to be a second-class citizen.

With that said, here's how I (as a user) would rank my opinion of the options @nikgraf listed (from my favorite to least favorite):

1. Import from a subdirectory 'polished/camelCase' (can alias with webpack/babel if you want)
2. Two different libraries generated from one source code with two dedicated docs pages.
3. An argument in every function which it's relevant
4. A global setting for all polished functions

**Comment by mxstbr** [comment]
Why don't we use `camelCase`? `styled-components` supports that perfectly fine? https://www.webpackbin.com/bins/-Kjqz5YRz2-dp7NREedN

**Comment by bhough** [comment]
> Well, it appears that the original/primary use-case for polished was to be used with styled-components.

Actually @kentcdodds, our goal is to make it work across the board, so no concerns there.

I've done some digging and verified that at least the major libraries `styled-components`, `aphrodite`, `jss`, `react-jss`, `glamor`, & `glamorous` all support and prefer `camelCase`. With `styled-components` also allowing it, we should be fine to move forward with this.

**Comment by nikgraf** [comment]
Cool! Let's camelCase then 😄

**Comment by bhough** [comment]
Addressed by #170

**Comment by bhough** [comment]
✨ polished 1.3 moves to camel-casing and is out now: https://github.com/styled-components/polished/releases/tag/v1.3.0
