### ISSUE TITLE
[V2] Integration Tests

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#172]
Add a suite of integration tests ensuring the CSS generated by ✨`polished` mixins works as expected with various CSS in JS implementations. Off the top of my head list:

- [ ] `styled-components` 
- [ ] `glamor`
- [ ] `glamorous`
- [ ] `aphrodite`
- [ ] `jss`
- [ ] `styled-jsx`
- [ ] `inline styles`

Open to suggestions for other popular libraries that we should run integration tests against.

**Comment by nikgraf** [comment]
Makes sense!
