### ISSUE TITLE
[V2] Add Types for TypeScript

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#174]
Add, and automatically check, types for TypeScript and Reason

- [ ] TypeScript
- [ ] Reason

**Comment by rohmanhm** [comment]
Still no improvement here. Anyone work for this feature?

**Comment by mxstbr** [comment]
> _Still_ no improvement here.

It's been five days my friend, and we all have full-time jobs :wink: in case you're interested in this feature we'd love somebody taking on the Reason types!

**Comment by rohmanhm** [comment]
> It's been five days my friend
Oops, I don't see it.

Some folks work on it.
https://github.com/styled-components/polished/pull/154

**Comment by thejameskyle** [comment]
@mxstbr I just added you to a project I'm working on which will help here.

**Comment by nikgraf** [comment]
@thejameskyle looking forward to it - do you have rough idea when you it's ready for prime time? :)

**Comment by bhough** [comment]
Addressed by #236
