### ISSUE TITLE
[V2] [Discussion] Contributor Experience Improvements

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#177]
Some items I'd like to discuss for V2 to help our day to day development workflow:

- [x] Implement prettier
- [x] NPM publish audit (users are indicating we may still be publishing unnecessary files to npm)
- [x] Cleanup Build Scripts (we keep ending up with an out of date bundle checked into the repo)
- [x] Replace ghooks [DEPRECATED] with husky

**Comment by mxstbr** [comment]
>  Remove semantic-release

Why do we want to remove that? I quite like not having to go through and publish each change manually...

**Comment by bhough** [comment]
> Why do we want to remove that? I quite like not having to go through and publish each change manually...

@mxstbr I don't feel super strong about this one. @nikgraf and I were just talking at ReactConf that sometimes it can be a bit cumbersome to work with. For example, we had a few releases get missed due to mistyped commit messages by contributors (that were manually doing the format instead of using commitizen). Also a standing question about how we use it to generate whole point releases. 

I'm not opposed to sticking with it, just wanted to discuss those points.

**Comment by bhough** [comment]
Just a note that I'm still evaluating some of the changes made specifically to the build script. The one challenge with building the docs on every commit is that it makes rebasing a bit of a nightmare as every commit ends up with some sort of conflict you have to account for when rebasing.

**Comment by nikgraf** [comment]
@bhough since all of them are checked, can we close this issue?

**Comment by bhough** [comment]
@nikgraf Yeah for now, I may tweak the precommit script but that can be done separately.
