### ISSUE TITLE
Mixin not working in styled-components conditional style

### ISSUE THREAD

**Issue by vizFlux** [styled-components/polished#180]
In this case, ellipsis will not be working...

```JavaScript
import { ellipsis } from 'polished';

export const Subheader = styled.h2`
    ${props => props.foo && `
        ${ellipsis('312px')}
        color: ${color.blue};
    `}
`;
```

```JSX
<Subheader foo>
    This one is a really long subheader I suppose!
</Subheader>
```

**Comment by bhough** [comment]
Hi @vizFlux, your issue is that you are returning an interpolation within an interpolation which requires the `css` helper in `styled-components`: https://github.com/styled-components/styled-components/blob/master/docs/api.md#css

Once you do that, it should work just fine: https://www.webpackbin.com/bins/-KkkT31cIhxnIUZBRrFj

**Comment by vizFlux** [comment]
@bhough Appreciate the explanation, perhaps I should take a sec back to understand how template literal really work. Thanks for the assistance and it has been helpful!

**Comment by chhuang** [comment]
How about this:

```js
${ props => props.color && css`
  background-color: ${ lighten(0.8, props => props.color) };
`};

// Passed an incorrect argument to a color function, please pass a string representation of a color.
```

Also tried:

```js
${ props => props.color && css`
  background-color: ${ lighten(0.8, `${ props => props.color }` ) };
`};

// Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.
```

**Comment by bhough** [comment]
@chhuang You are getting that error because you are passing it a function as opposed to just the color prop. It should look like this:

```javascript
background-color: ${props => props.color && lighten(.5, props.color)}
```

**Comment by chhuang** [comment]
Thanks @bhough, that makes sense.

**Comment by misstricky** [comment]
Hello! I tried the above, and while it works in the browser, when I try to use `.render()` in jest tests on components containing:
```${props => props.color && darken(.1, props.color)}```
I still get the error:
```Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.``` and the test fails with that error. Is there any way around this? Thanks!

**Comment by bhough** [comment]
@misstricky do you have this code somewhere I can look at?

**Comment by maximus-lynn** [comment]
This doesn't work for me... I'm getting a lighten undefined

**Comment by bhough** [comment]
@maximus-lynn can you provide an example where you are seeing this error?

**Comment by buddikastay** [comment]
Hi, 

Im calling a function to get the button face/type. So relevant color will be called on hover and i want to darken That-returned color. 

i'm getting 'Passed an incorrect argument to a color function, please pass a string representation of a color.'

im using react-emotion in my app.
 
Please help to find out the issue,

style.js

function getButtonTextColor({face, status, theme}) {
    let buttonTextColor;
    let buttonFace = _getButtonFace({face, theme});

    switch( true ) {
        case (status === 'warning') : buttonTextColor = `${buttonFace.buttonTextColor}`; break;
        case (status === 'error') : buttonTextColor = `${buttonFace.buttonTextColor}`; break;
        default: buttonTextColor = `${buttonFace.buttonTextColor}`
    }
    return buttonTextColor;
}


export const ButtonBase = styled('button')`
    display: flex;
    align-items: center;
    justify-content: center;
    outline: none;
    cursor: pointer;
    color: ${getButtonTextColor};
   
    &:hover {
        color: ${darken(0.1, getButtonTextColor)};
        background: ${props => props.theme.primaryDarkColor};
    }
    &:active {
        background: ${props => props.theme.primaryColor};
    }
`;

**Comment by bhough** [comment]
@buddikastay you aren't actually calling the `getButtonTextColor` function. `polished` will not evaluate functions that it is passed, so you need to evaluate it when you pass it:

`color: ${darken(0.1, getButtonTextColor(...))};`

**Comment by buddikastay** [comment]
@bhough : sorted it out. This worked.

color: ${props => darken(0.4, getButtonTextColor(props))};

Thanks a lot for your valuable time. Cheers!
