### ISSUE TITLE
`babel-preset-latest` is deprecated

### ISSUE THREAD

**Issue by luftywiranda13** [styled-components/polished#195]
- `polished` version: v1.1.3

polished still uses `babel-preset-latest` which is deprecated. Babel suggests to migrate to `babel-preset-env`.
![screen shot 2017-06-18 at 00 05 44](https://user-images.githubusercontent.com/22868432/27254783-195fb2ce-53ba-11e7-9cae-05a6d44f5340.png)
https://babeljs.io/docs/plugins/preset-latest/

**Comment by mxstbr** [comment]
PR welcome!

**Comment by luftywiranda13** [comment]
@mxstbr done 👍

**Comment by bhough** [comment]
Addressed by #203
