### ISSUE TITLE
Install Flow Lib Defs

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#200]
We have not installed Flow libdefs for our dependencies. These leads to flow errors with our source code (#197). 

We just need to run `flow-typed install` and commit the downloaded lib defs.

**Comment by luftywiranda13** [comment]
i did it on https://github.com/styled-components/polished/pull/196/commits/53261fdb8ab922d725792f5b78b6c1cbdebe6f88

**Comment by bhough** [comment]
@luftywiranda13 yep I created #202 for that.
