### ISSUE TITLE
Create Flow Library Definitions and add them to flow-typed

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#202]
In order to better support users who use `flow` for their projects we should create library definitions for `✨ polished` and add them to `flow-typed`.

- [ ] Creating libdefs: https://flow.org/en/docs/libdefs/creation/
- [ ] Adding to `flow-typed`: https://github.com/flowtype/flow-typed
- [ ] Add instructions for installing types to flow section of README.md

**Comment by bhough** [comment]
#222 gives us first-class Flow Support in https://github.com/styled-components/polished/releases/tag/v1.5.0 with zero configuration. This issue is still valid as libdefs will give us better type-ahead support in most code editors.

**Comment by laurenskling** [comment]
I see all the `.flow` files in my node_modules, but still flow gives me:
```
 5: import { parseToRgb, toColorString } from 'polished';
                                               ^^^^^^^^^^ polished. Required module not found
```
what am i mssing?

**Comment by oliverjam** [comment]
Yeah I'm seeing the same error as @laurenskling. The README implies Flow should be supported out of the box (other than ignoring `.*/node_modules/polished/.*`). It seems like Flow isn't picking up any types (using Polished `1.9.1`)

**Comment by bhough** [comment]
Thanks for the update @oliverjam. This is almost always caused by an ignore rule that is ignoring too much.

**Comment by bhough** [comment]
Flow is now working out of the box with the package without the need for third party libdefs.
