### ISSUE TITLE
Contrast support

### ISSUE THREAD

**Issue by sergeyzwezdin** [styled-components/polished#206]
It would be useful to have `contrast` mixin support out of the box.

This is how it's implemented in SASS: http://compass-style.org/reference/compass/utilities/color/contrast/

**Comment by bhough** [comment]
Thanks for the issue @sergeyzwezdin. Good news is this has already been implemented as part of V2 #185

**Comment by sergeyzwezdin** [comment]
Cool. When v2 will be released?

**Comment by bhough** [comment]
@sergeyzwezdin Hopefully in the next couple weeks. It is likely that I will cut the scope of V2 to get it out sooner, as things like this, css-locks, and camelCasing are in high demand.
