### ISSUE TITLE
[Feature Request] Font-Smoothing Mixin

### ISSUE THREAD

**Issue by emattias** [styled-components/polished#209]
How about adding a cross browser font smoothing helper?

Relevant links:
- https://gist.github.com/hsleonis/55712b0eafc9b25f1944
- https://codepen.io/gregh/pres/PWwoVd
- https://davidwalsh.name/font-smoothing
- https://medium.com/@MateMarschalko/improving-font-rendering-with-css-3383fc358cbc

**Comment by bhough** [comment]
Closing due to lack of interest.
