### ISSUE TITLE
Convert between units helper

### ISSUE THREAD

**Issue by emattias** [styled-components/polished#212]
I would have use for a helper that converts between units.

Relevant links:
- https://2012.heygrady.com/blog/2011/12/21/length-and-angle-unit-conversion-in-javascript/
- https://github.com/heygrady/Units

**Comment by bhough** [comment]
Upon reviewing this, we are going to elect not to put this in polished. Given it requires knowledge of the surrounding DOM to make calculations, that is not something we want to have polished concerned with.
