### ISSUE TITLE
Is there a helper for 'display'?

### ISSUE THREAD

**Issue by joetidee** [styled-components/polished#213]
I have this equivalent CSS:
```
display: -webkit-box;
display: -moz-box;
display: -ms-flexbox;
display: -moz-flex;
display: -webkit-flex;
display: flex;
```

I was hoping there was a helper 'display' that would work like this:

`display('flex')`

**Comment by bhough** [comment]
@joetidee We don't provide this (or most other prefix only helpers) because most of the JS-in-CSS libraries take care of vendor prefixing on their side.

**Comment by joetidee** [comment]
ok, thanks.
