### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by guzart** [styled-components/polished#23]
Planning on using flow type?

**Comment by mxstbr** [comment]
Hmm, haven't thought about it. We probably won't use it in the code itself but I wouldn't mind adding flow typing for others to use!

**Comment by relekang** [comment]
Why not use it in the code? I haven't looked that much in this repo yet. I have time to do a PR for this tomorrow.

**Comment by mxstbr** [comment]
Because there isn't much code that we use throughout the codebase, almost every function is an external API, so flowtypes within the codebase would be pretty useless

**Comment by relekang** [comment]
I think there are a few benefits:
* It is easier to keep the types up to date, we test that the types actually work if we have `@flow` our test files.
* Making sure the data in the tests is still applicable.
* It is much easier to iron out the enhancement of exporting of types in a smaller repo like this than the styled-components repo 🙂

**Comment by guzart** [comment]
That is precisely why I was asking, I was about to start working on a PR when I thought it would be nice to have flow type support form the start.

**Comment by mxstbr** [comment]
Okay, I'm convinced, sounds good to me! Feel free to ahead with a PR!

**Comment by guzart** [comment]
Too bad I can't help with this, my flow xp is very low. Looking forward to learn from the commit tho =D
