### ISSUE TITLE
Add helper to add `px` to numbers

### ISSUE THREAD

**Issue by AndersDJohnson** [styled-components/polished#234]
It'd be nice to have a small helper that would convert numbers into strings with `px` suffix, but leave strings in-tact (assuming they match `^/-?\d+\s*px$/`, otherwise perhaps warn or error). Like the inverse of `stripUnit`. Then consumers could pass pixel props as either numbers or strings.

Something like [add-px](https://www.npmjs.com/package/add-px) or [pixelify](https://www.npmjs.com/package/pixelify).

**Comment by bhough** [comment]
@AndersDJohnson thanks for this issue. It is something we've started discussing as part of #223 if you want to join in on that discussion. Going to close this in favor of that discussion.
