### ISSUE TITLE
Typescript and tsgen should be devDependencies instead of dependencies

### ISSUE THREAD

**Issue by signallinden** [styled-components/polished#240]
I recently brought `polished` into a project and noticed a lot more dependencies being installed than previous versions.

#236 introduced `typescript` and `tsgen` as __dependencies__ rather than __devDependencies__. This may have been a mistake, as neither packages are needed to run `polished`.

Affected versions: 1.6.0, 1.6.1

**Comment by bhough** [comment]
Thanks for catching this @signallinden. Fixed by 1.6.2 (#241)
