### ISSUE TITLE
Unneccessary enforcement of string type?

### ISSUE THREAD

**Issue by emattias** [styled-components/polished#246]
I am using `polished` with `glamorous` so I have all my px values as numbers which works (atleast for my use cases), so why are string enforced? See this line to see what I mean:

https://github.com/styled-components/polished/blob/c07f57ea89da1820e4cb619cccefcced74b60614/src/helpers/directionalProperty.js#L52

It could be changed to `...values: Array<?string | ?number>` no?

**Comment by dlwalsh** [comment]
This is coming in version 2. See https://github.com/styled-components/polished/pull/166

https://github.com/styled-components/polished/blob/0b9f27fa8f41419117470ec90ac5555d152b6f0a/src/helpers/directionalProperty.js#L50

**Comment by bhough** [comment]
@emattias @dlwalsh I will probably be bringing this into v1 in the next week or 2 given that v2 has stalled some. Most non breaking changes from that branch will be ported over to v1 (already don't that with some things)

**Comment by bhough** [comment]
Addressed by #255
