### ISSUE TITLE
Webpack file loader + fontFace

### ISSUE THREAD

**Issue by DavidBachmann** [styled-components/polished#257]
I am unable to require font files with webpack's file loader because `fontFace` expects a file name without an extension resulting in double extensions.

I was thinking of doing a PR that would allow `fileFormats: null` and skip appending file extensions.
Any other ideas?

- `polished` version: 1.8.0
- `JSS-in_CSS` library and version: styled-components 2.1.2
- Any relevant JS library and version: React 16

Mixin/Helper/Shortand you were using and how you were using it:

```javascript
import { injectGlobal } from 'styled-components'
import { fontFace } from 'polished'

const fontFamily = [
  { name: 'DINWeb-Regular', style: 'normal', weight: 400, type: 'woff' },
  { name: 'DINWeb-Italic', style: 'italic', weight: 400, type: 'woff' },
  { name: 'DINWeb-Light', style: 'normal', weight: 300, type: 'woff' },
  { name: 'DINWeb-Medium', style: 'normal', weight: 500, type: 'woff' },
  { name: 'DINWeb-Bold', style: 'normal', weight: 600, type: 'woff' },
]

const fonts = injectGlobal`${  
  fontFamily.map(font => fontFace({
    'fontFamily': 'DINWeb',
    'fontFilePath': require('../../assets/fonts/' + font.name + '.' + font.type),
    'fontWeight': font.weight,
    'fontStyle': font.style,
  }))
}`

export default fonts
```

What you are seeing:

![image](https://user-images.githubusercontent.com/8494120/31548785-9f350ee0-b01b-11e7-9a55-bef3722bf778.png)

What you expected to see:

Successfully loaded font files

**Comment by bhough** [comment]
@DavidBachmann I would definitely be interested in seeing a PR. One question I have is if you wanted to load multiple font formats using this method, would we also need to modify `fontFilePath` to accept an array?

**Comment by DavidBachmann** [comment]
@bhough Good question. My initial thought was if I opted out of the `fileFormats` helper it would be up to me to load the appropriate font formats.

**Comment by bhough** [comment]
@DavidBachmann Agreed, right now we wouldn’t be able to do that, since it assumes a single file path and uses the array of extensions to generate the list. We’d need to generate that list from an array on the `fontFilePath` key.

**Comment by fiznool** [comment]
Was this ever resolved? Struggling to understand how to use `fontFace` with the webpack file-loader.

**Comment by bhough** [comment]
@fiznool we have not heard enough noise around this to prioritize the work. We would consider a PR for this addition, but as of now it is not on our radar.
