### ISSUE TITLE
Adding more mixins and helpers

### ISSUE THREAD

**Issue by kitze** [styled-components/polished#26]
I wrote something similar a while ago and I'm using it with another css-in-js library (aphrodite).

https://github.com/kitze/stylz/tree/master/src

Do you think we can combine efforts and merge the libraries?

**Comment by mxstbr** [comment]
Yes, please!! Have you seen #1? Which ones are missing, and which ones do you have already?

**Comment by bhough** [comment]
Closing this for now. @kitze feel free to submit a PR for any items you think we should add from your library.
