### ISSUE TITLE
Mixin typescript definitions are not compatible with styled-components

### ISSUE THREAD

**Issue by zaboco** [styled-components/polished#261]
- `polished` version: 1.8.1
- `JSS-in_CSS` library and version: styled-components 2.2.1
- Any relevant JS library and version: 
  + React 16.0.0
  + Typescript 2.5.3

#### Mixin/Helper/Shortand you were using and how you were using it:

- I was using `normalize`, but any other mixin that returns an `Object` has the same issue.

```typescript
import { normalize } from 'polished';
import { injectGlobal } from 'styled-components';

injectGlobal`${normalize()}`;
```

#### What you are seeing:

When compiling this code with Typescript, I get:
```
error TS2345: Argument of type 'Object' is not assignable to parameter of type 'SimpleInterpolation'.
  The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
...
```

#### What you expected to see:

The code should compile with Typescript.

**Comment by mxstbr** [comment]
Duplicate #1123

**Comment by vhfmag** [comment]
Hello, @mxstbr! While the mentioned styled-components' PR (not accepting object types as interpolation values) was indeed a cause of this issue, it still wasn't solved with its merge. As of now, `injectGlobal` type definitions are:

```ts
export type InterpolationValue = string | number | Styles | FalseyValue | StyledComponentClass<any, any>;
export type SimpleInterpolation = InterpolationValue | ReadonlyArray<InterpolationValue | ReadonlyArray<InterpolationValue>>;
export injectGlobal(strings: TemplateStringsArray, ...interpolations: SimpleInterpolation[]): void;
export interface Styles {
  [ruleOrSelector: string]: string | number | Styles;
}
```

`Styles` is the interface that adds support for style objects, and it's not compatible with the return type of most `polished` mixins, like `normalize`, whose return types are often just `Object`. Being too general, Object is not compatible with `Styles` and Typescript still throws the same error.

As such, I would ask you to reopen this issue. I can submit a PR fixing this, if that's desirable. I think `Styles`, as defined in `styled-components`, already describes well the type of the values returned by most polished functions, so it shouldn't be much more than a copy and paste.

Thanks!

**Comment by vhfmag** [comment]
Ok, I don't know if I really can open a PR, given that TS's type definitions are derived from Flow's and how little I know about the later. I'll still try, though :)
