### ISSUE TITLE
Polished in project with Flow (Required module not found) error

### ISSUE THREAD

**Issue by FerryKobus** [styled-components/polished#269]
- `polished` version: 1.8.1
- `JSS-in_CSS` library and version: 2.2.1
- Any relevant JS library and version: react: 16, flow-bin: 0.54.0, flow-typed: 2.2.0

We use flow-typed to generate the stubs automatically with `flow-typed install`

Line of code that breaks in flow:
```javascript
import { parseToRgb, toColorString } from 'polished';
```

When running flow, i get an error that polished module is not found.
I've tried adding polished to the .flowconfig [ignore] block like discussed in #239 

Still get the following error:
```shell
Launching Flow server for /app
Spawned flow server (pid=196)
Logs will go to /tmp/flow/zSapp.log
Error: src/components/row/row.styled.js:5
  5: import { parseToRgb, toColorString } from 'polished';
                                               ^^^^^^^^^^ polished. Required module not found
```
Only option to remove the error is running:

`flow-typed create-stub polished@1.8.1`

**Comment by relekang** [comment]
If you ignore polished in flowconfig flow will not find it unless you have an libdef. Since there are no libdef for it yet stubbing is necessary.

**Comment by FerryKobus** [comment]
So the only way to solve this problem is to manual create the stub?

**Comment by bhough** [comment]
@FerryKobus `polished` has first class flow support and should not need stubbing or flow-typed. Flow-Typed was intended for libraries without native flow support. I'm not able to look right away, but a good place to start might be that when you create stubs for all your dependencies, it may keep flow from picking up the native definitions that are built-in. Maybe try removing the `polished` folder from your `flow-typed` folder completely.

**Comment by thabemmz** [comment]
I run into the same issue. The `polished` folder isn't included in the `flow-typed` folder, so it does not seem to be a problem with `flow-typed`.

**This is the setup I am using:**

`polished` version: 1.8.1
`JSS-in_CSS` library and version: 2.2.1
Any relevant JS library and version: `react`: 16, `flow-bin`: 0.54.0, `flow-typed`: 2.2.0

My flowconfig:
```
[ignore]
.*/node_modules/jest-in-case/*
.*/node_modules/radium/*
.*/node_modules/eslint-plugin-jsx-a11y/*
.*/node_modules/styled-components/*
.*/storybook-static/*
.*/lib/*

[include]

[libs]

[lints]

[options]
```

When running `flow-typed install`, there does not occur a `polished` file within the `flow-typed` folder, but I still get the following error when running `flow`:

```
  12: import { parseToRgb } from 'polished';
                                               ^^^^^^^^^^ polished. Required module not found
```

**Comment by thabemmz** [comment]
We resolved this issue. It was being caused by the `.*/lib/*` line in the ignore from `.flowconfig`. This is the `.flowconfig` that works for us:

```
[ignore]
<PROJECT_ROOT>/node_modules/jest-in-case/*
<PROJECT_ROOT>/node_modules/radium/*
<PROJECT_ROOT>/node_modules/eslint-plugin-jsx-a11y/*
<PROJECT_ROOT>/node_modules/styled-components/*
<PROJECT_ROOT>/storybook-static/*
<PROJECT_ROOT>/lib/*
```

**Comment by FerryKobus** [comment]
Thanks @thabemmz that resolves the issue for me too!
