### ISSUE TITLE
Feature Request: Calculating with unit-suffixed values

### ISSUE THREAD

**Issue by tobilen** [styled-components/polished#270]
If i want to perform arithmetic on values that have a unit suffix, i can do it like so in sass:
```ssss
$base: 12px;
$double: 2 * $base;
```

while there isnt really an easy way to make this work in js, polished could provide helper functions that take care of the necessary regex to strip the unit, perform the calculation and return a the result as a string with the original unit. the main benefit here would be that the unit type is retained, which it wont be if `stripUnit` is used.

Mock usage:
```js
import { multiply, add } from 'polished';

const base = '12px';
const double = multiply(base, 2); // returns '24px'

const one = '1px';
const plusOneplusOne = add(base, one, one); // returns '14px'
```

It could also have an [idx](https://github.com/facebookincubator/idx)-like syntax:
```js
import { calc, stripUnit } from 'polished';

const  base = '12px';
const double = calc(base, baseAsNumber => baseAsNumber * 2); // returns '24px'

const one = '1px';
const plusOne = calc(base, baseAsNumber => baseAsNumber + stripUnit(one)); // returns '13px'
```

**Comment by caribou-code** [comment]
I've seen a few similar issue tickets and this linked PR all closed without resolution. Why is this?

Being able to perform calculations on values with units is one of the most basic features in SCSS and I don't see the point in extending styled components functionality with Polished unless it has this sort of thing.
