### ISSUE TITLE
Add Linear Gradients helper

### ISSUE THREAD

**Issue by mjsisley** [styled-components/polished#284]
It would be nice to have a `linear-gradient` helper within polished.

https://github.com/JSBros/uigradients is a utility that does this (for pre-made, community curated gradients), however their bundling leads to very large bundle sizes (https://github.com/JSBros/uigradients/issues/23). 

It would be nice if a linear-gradient utility was brought into `polished` (and could also make use of the bundling, `babel-plugin`, etc that come with this centralized utility lib).

**Comment by mjsisley** [comment]
I believe the stars on that project should imply community interest.

**Comment by bhough** [comment]
This has been added to the V3 Roadmap (#354).
