### ISSUE TITLE
font-display in the fontFace helper

### ISSUE THREAD

**Issue by oliverjam** [styled-components/polished#286]
First of all thanks for the great library; it's saved us loads of time.

Would anyone object to including [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) in the `fontFace` helper?

We want to start using it as a progressive enhancement, so happy to put together a PR for this?

While I'm at it would it be worth adding `font-variation-settings` and `font-feature-settings` too? They're the only other `@font-face` rules missing.

**Comment by bhough** [comment]
Thanks @oliverjam, happy to hear you are getting good use out of polished.

Definitely would welcome a PR to enhance `fontFace` with all three!

**Comment by oliverjam** [comment]
Sorry that took a while but #287 is up now.

I had an issue committing—`lint-staged` would only run once I removed the `--verbose` option from the npm script. I'm not sure if they've removed that option but I kept getting `unknown option '--verbose'`

**Comment by bhough** [comment]
Addressed in 2.0: https://github.com/styled-components/polished/milestone/1
