### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by mac-s-g** [styled-components/polished#292]
relevant dependencies:

- `polished` version: 1.9.1
- `JSS-in_CSS` library and version: styled-components 2.4.0
- Any relevant JS library and version: react 16.2.0

issue:
updating polished from 1.9.0 to 1.9.1 causes the following error at runtime:
```
Uncaught ReferenceError: exports is not defined
    at Object.eval (polished.es.js?435d:8)
```
I locked all my dependencies to verify that polished 1.9.0 -> 1.9.1 is causing the issue.

this is preventing my app from running at all.

it looks like updates from 1.9.1 added an implicit runtime dependency on CommonJS.

I'll look through some recent diffs to see if I can identify the culprit.

_I love this project! thanks for opening it up to the world!_

**Comment by mac-s-g** [comment]
likely coming from #288

**Comment by Andarist** [comment]
Working on the fix.
