### ISSUE TITLE
Doc theme

### ISSUE THREAD

**Issue by mxstbr** [styled-components/polished#31]
We definitely need a nicer theme for the documentation.

The things people will come to the docs site for are:

1. Find a list of supported helpers
2. Find out how to use a certain helper
3. Find out which options a certain helper has

The current theme a) doesn't look very inviting (needs a nicer color scheme, we can probably just take the `styled-components` one) and b) takes actual brain power to understand how to use a certain helper. I like the sidebar, and I like how the parameters are documented though. We should get rid of the `Returns` section though, as it's totally useless for our purposes.

For reference, here are the [Bourbon docs](http://bourbon.io/docs/) which are pretty clear and easy to understand:

![screen shot 2016-12-08 at 16 20 33](https://cloud.githubusercontent.com/assets/7525670/21015465/5b4d1eea-bd62-11e6-8ed0-d57eef301b81.png)

I like their ideas for the header, instead of our massive violet wall of color and text it should also just say "Ellipsis" on the left side and link to the source on the right side.

Maybe @okonet has some ideas for this?

**Comment by mxstbr** [comment]
Something that would be really cool is to have live REPLs (maybe embedded JSBins/JSFiddles/Codepens/...) which show the helper usage on the left, and the live output what it returns on the right. That way people coming to the docs can only see an example of usage but also play around with it! 😱 💯

**Comment by mxstbr** [comment]
We should also use a syntax highlighter that supports ES6. (the `${timingFunction}` here should be highlighted as JS code again)

![screen shot 2016-12-08 at 16 48 18](https://cloud.githubusercontent.com/assets/7525670/21016535/2bd8e7bc-bd66-11e6-8e95-649e47fec465.png)

**Comment by mxstbr** [comment]
Should we switch to using [documentation.js](https://www.npmjs.com/package/documentation)? They support Flow, meaning we don't duplicate any information between the comments and the flow types which is super rad, ES7+ and has a GitHub integration – in general it just sounds much better than JSDoc!

I haven't really dug in, but what do you think @bhough? Do you reckon we should do that or is our JSDoc setup so intricate it will take ages to replicate it?

**Comment by bhough** [comment]
@mxstbr I believe it works with JSDoc syntax, so superficially it should be a fairly easy transitions. How the template would hold up would be another story. However, if someone picks up this up, that would be moot.

**Comment by mxstbr** [comment]
Switched to documentation.js, inlining the default theme with #54! Would be 👌 to get some design for the homepage and the docs page

**Comment by okonet** [comment]
I can take a look at design next week.

**Comment by bhough** [comment]
Going to close this for now, though may be part of a V2 docs revamp.
