### ISSUE TITLE
css triangle optimizations

### ISSUE THREAD

**Issue by lifeiscontent** [styled-components/polished#313]
- `polished` version: latest

What you are seeing:

in the example

```
// Styles as object usage

const styles = {
  ...triangle({ pointingDirection: 'right', width: '100px', height: '100px', foregroundColor: 'red' })
}


// styled-components usage
const div = styled.div`
  ${triangle({ pointingDirection: 'right', width: '100px', height: '100px', foregroundColor: 'red' })}


// CSS as JS Output

div: {
 'borderColor': 'transparent',
 'borderLeftColor': 'red !important',
 'borderStyle': 'solid',
 'borderWidth': '50px 0 50px 100px',
 'height': '0',
 'width': '0',
}
```

What you expected to see:

rather than using !important for the borderLeftColor, I think the long hand border properties would be better here, I think we could achieve this by introducing a new helper that splits css values like `100%` and returns either a array or object that gives you the value and the unit. so you can do the following things:

1. specify a triangle that isn't based on pixels.
2. specify a triangle without the `!important`

if this sounds like something this library wants, I'll create a PR.

if you have any suggestions on names for the unit parser function, let me know. my initial thought is calling it `cssLength` as thats what the unit as a whole is called in the CSS Spec, but it does sound a bit weird as well.

Reproduction:

**Comment by bhough** [comment]
@lifeiscontent These certainly could be useful improvements, so would welcome a PR.

Instead of a separate unit parser, I've had a long-standing thought to modify the `stripUnit` helper to have the option to return the striped unit. That may be a good place to start.

**Comment by lifeiscontent** [comment]
@bhough cool, I'll take a look into `stripUnit` and tell you my suggestions shortly.

**Comment by lifeiscontent** [comment]
@bhough actually, on second thought, the name `stripUnit` doesn't really imply you'll get a unit back, based off the name it makes me inclined to create another helper, let me know your thoughts.

**Comment by bhough** [comment]
@lifeiscontent I'd move forward assuming we will use `stripUnit`. I will have to dig it up, but we've had a long discussion about this before. In the end you will recreate a lot of the same functionality in the new version that will be produce the same results it does. We can look at splitting it later once we see what the final approach is.
