### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mxstbr** [styled-components/polished#32]
I remember @okonet showing us a screenshot of an amazing logo somewhere, could we get that exported and added to the repo somewhere in png and svg?

**Comment by okonet** [comment]
You should watch your own repos :) It's been done a month ago.

Here you go https://github.com/styled-components/brand/blob/master/polished.svg

Also I've updated font for both logos so you might want to update the styled-component everywhere.

**Comment by mxstbr** [comment]
Oh ooops, nice one! Sorry about that 🙈

**Comment by okonet** [comment]
😎
