### ISSUE TITLE
Change triangle mixin to works with others measurement units

### ISSUE THREAD

**Issue by horaciosystem** [styled-components/polished#326]
The **triangle** mixin has pixel unit hardcoded inside the _getBorderWidth_ function, as you can see [here](https://github.com/styled-components/polished/blob/master/src/mixins/triangle.js#L21) 
What means that in a project using _rem_ unit the triangle size will not scale in accordance to the rest of the app.

My suggestion is to remove the pixel unit =>
Current
```js
    case 'top':
      return `0 ${width / 2}px ${height}px ${width / 2}px`
    case 'left':
      return `${height / 2}px ${width}px ${height / 2}px 0`
    case 'bottom':
      return `${height}px ${width / 2}px 0 ${width / 2}px`
    case 'right':
      return `${height / 2}px 0 ${height / 2}px ${width}px`
```

 To
```js
    case 'top':
      return `0 ${width / 2} ${height}px ${width / 2}`
    case 'left':
      return `${height / 2} ${width} ${height / 2} 0`
    case 'bottom':
      return `${height} ${width / 2} 0 ${width / 2}`
    case 'right':
      return `${height / 2} 0 ${height / 2}px ${width}`
```
Does anyone see any problem with this ?

**Comment by bhough** [comment]
Thank you for the suggestion @horaciosystem. This is already on the way in 2.0: https://github.com/styled-components/polished/commit/2c89e3eba228004e86a06162d097281b4433e846#diff-a1597c288b2bf10e94bdd55e61657af7
