### ISSUE TITLE
When use ${wordWrap('break-word')}, result includes word-break: break-all;

### ISSUE THREAD

**Issue by RoboQuasar** [styled-components/polished#330]
- `polished` version: 
- `JSS-in_CSS` library and version: 
- Any relevant JS library and version: 

I want to use polished lib for cross-browser compatibility css `word-wrap` and get unexpected css-property `word-break: break-all`, which work correct, but uncomfortable for most using ways in Chrome (67.0.3396.99)
Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
${wordWrap('break-word')}
```

What i am seeing:

```javascript
 overflow-wrap: break-word;
 word-wrap: break-word;
 word-break: break-all;
```

What am i expected to see:
```javascript
  overflow-wrap: break-word;
  word-wrap: break-word;
```

Is it correct behavior and for my goal i need to use some other lib? 
Or something went wrong?

**Comment by bhough** [comment]
Thanks for the question @RoboQuasar. That is on purpose. It handles use cases like: https://stackoverflow.com/questions/1795109/what-is-the-difference-between-word-break-break-all-versus-word-wrap-break/19282567#19282567
