### ISSUE TITLE
Typings are incompatible with styled-components

### ISSUE THREAD

**Issue by Ky6uk** [styled-components/polished#348]
- `polished` version: 2.0.0
- `JSS-in_CSS` library and version: styled-components 3.4.4
- TypeScript: 3.0.1

Mixin/Helper/Shorthand you were using and how you were using it:

```typescript
injectGlobal`
  ${normalize()};
  ${ellipsis()};
  // ...
`;
```

What you are seeing:

Compilation Errors:

```
TS2345: Argument of type 'Styles' is not assignable to parameter of type 'SimpleInterpolation'.
  Type 'Styles' is not assignable to type 'ReadonlyArray<string | number | false | Styles | StyledComponentClass<any, any, any> | ReadonlyArray<InterpolationValue>>'.
    Property 'length' is missing in type 'Styles'.
```

and 

`TS2352: Type 'Styles[]' cannot be converted to type 'Styles'.`

---

Not sure this is a `polished` or `styled-components` issue, because supporting `polished` by consumers is a problem of consumers I guess.

Anyway typecasting to `Styles`/`Styles[]` interface imported from `styled-components` helps.

**Comment by bhough** [comment]
@Ky6uk #331 was an attempt to address this, as it has been the case for awhile (#261). We will keep digging in to see if there is a way to address this without having to recast.

**Comment by Ky6uk** [comment]
@bbohen I think this is clear. 

### `styles-components`

```typescript
export interface Styles {
  [ruleOrSelector: string]: string | number | Styles
}
```

### `polished`

```typescript
interface Styles {
  [ruleOrSelector: string]: string | number | Styles | Array<Styles>;
}
```

As we can see `styled-components` version of interface doesn't support `Styles[]`.

Adding a ` | Styles[]` to the type definition of `styled-components` fixes this issue.

**Comment by bhough** [comment]
@Ky6uk yes, but that is a fix out of our control, and we don't know the implications that will have on `styled-components`.

**Comment by Ky6uk** [comment]
@bhough removing the `| Array<Styles>` from `polished` also possible fix. But I am not sure this is idiomatically right.
