### ISSUE TITLE
Support of 4-digit hex color format in helpers

### ISSUE THREAD

**Issue by Gywem** [styled-components/polished#368]
Hello everyone!

I'm using many of the style helpers that offers this library in a CSS-IN-JSS context. The thing is that I have a color picker that generates color strings and the output is used for the polished helpers. Sometimes the user produces 4-digit in hex format. But the helpers of this library don't support that, or at least `darken` which is the one I tested. It throws the next error:

```
Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.
```

```
polished: 2.0.3
react: 16.4.2
JSS-in_CSS: none, just using a helper.
```

## Reproduction

I prepared a reproduction to show it, just press the 4-digit hex color and you will get the error displayed.
https://codesandbox.io/embed/qv3opq0wv6?view=preview

**Comment by bhough** [comment]
Thanks for reporting this @Gywem. All the color helpers use the same module to process color values and we did not add 4 digit shorthand support when we added support for 8-Digit, but this should be relatively trivial to implement in a future release.
