### ISSUE TITLE
Carry with props

### ISSUE THREAD

**Issue by byzg** [styled-components/polished#369]
- `polished` version: 2.0.3
- `JSS-in_CSS` library and version:  styled-components 3.3.2
- Any relevant JS library and version:  React 15.6.1

How can I use 
```javascript
import { theme } from 'styled-tools';
color: ${transparentize(0.79, theme('colors.blackMarlin'))};
```
except of
```javascript
import { theme } from 'styled-tools';
color: ${props => transparentize(0.79, theme('colors.blackMarlin')(props))};
```
?
I know, polished has carry but it does not help here

**Comment by bhough** [comment]
@byzg It is hard to tell from this example what exactly you are trying to accomplish with the second example. A quick look at styled-tools doesn't show me anything where they support `theme` being called with partial application, which it appears your code is trying to do).

Using our currying support would look more like this (though unnecessary in this case):

```javascript
color: ${transparentize(0.79)(theme('colors.blackMarlin'))};
```

**Comment by simonkberg** [comment]
Use `withProp` instead:
```js
import { withProp } from 'styled-tools';
...
color: ${withProp('theme.colors.blackMarlin', transparentize(0.79))};
```

**Comment by bhough** [comment]
Closing this with @simonkberg's answer. Let us know if we can help in anyway @byzg.

**Comment by byzg** [comment]
@bhough I mean I would like to know if I can use only `theme` with `transparentize` (and other helpers) without `props` and `withProp`. 
`theme` return a function with `props` as argument, so IMHO it would be very convenient to allow pass the second argument of `transparentize` as a function, somthing like this:


```javascript
function curriedTransparentize(amount, color) {
  return function(props) {
    var parsedColor = parseToRgb(typeof color === 'function' ? color(props) : color);
    ...
    return rgba(colorWithAlpha);
  }
}
```

PS: Unfortunately `color: ${transparentize(0.79)(theme('colors.blackMarlin'))};` 
still not working [Codesandbox](https://codesandbox.io/s/ll0n1y9l1l)

**Comment by bhough** [comment]
@byzg Right now we do not support evaluating functions passed as arguments into any of color modules. We would need to know the signature of the passed function in order to call it correctly, and we do not want to tie the implementation to a specific library (such as styled-tools).

**Comment by byzg** [comment]
Ok, I see. Thanks
