### ISSUE TITLE
Interpolation within interpolation 

### ISSUE THREAD

**Issue by ivorpad** [styled-components/polished#373]
- `polished` version: 2.1.1
- `JSS-in_CSS` library and version: gatsby-plugin-styled-components 3.0.0

### Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
const borderBottom = css`
  border-bottom: 2px solid ${lighten(0.3, `${props => props.theme.main.blue}`)};
`
```

### What you are seeing:

`Uncaught Error: Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation.`

### What you expected to see:

I expect the color string to be parsed correctly. Am I missing something? I can confirm `${props => props.theme.main.blue}` returns correctly a hex value.

**Comment by bhough** [comment]
@ivorpad It is just a formatting issue:

`const borderBottom = css`
    border-bottom: 2px solid ${props => lighten(0.3, props.theme.main.blue)};
``
https://codesandbox.io/s/64xvkrowvk
