### ISSUE TITLE
create-react-app

### ISSUE THREAD

**Issue by lifeiscontent** [styled-components/polished#374]
- `polished` version: polished@2.1.1
- `JSS-in_CSS` library and version: emotion@9.2.10
- Any relevant JS library and version: react@16.5.2

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
import {
  darken,
  em,
  lighten,
  margin,
  padding,
  transparentize,
  triangle
} from 'polished';

```

What you are seeing:

when using create-react-app@next I'm seeing the following error:

```
./node_modules/polished/dist/polished.es.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/lifeiscontent/Code/app/node_modules/polished/dist'
```

What you expected to see:

polished to work

Reproduction:

**Comment by lifeiscontent** [comment]
@bhough everything works fine in 2.0.3 I'm using create-react-app@latest.

**Comment by bhough** [comment]
Confirmed the issue:
2.0.3 works fine with cra@latest.
2.1.1 works fine with cra@latest.
2.0.3 works fine with cra@next
2.1.1 works fine with cra@next pre-webpack 4/babel 7 merge
2.1.1 breaks with cra@next post-webpack 4/babel 7 merge

My guess is this is our move to Babel 7 conflicting with their move to it in some way. @TrySound any thoughts here?

I will take a look this weekend and file a bug with them if I don't see anything obvious. Thanks for raising this @lifeiscontent.

**Comment by bhough** [comment]
@lifeiscontent update on this:

`yarn upgrade react-scripts@2.0.0-next.a671462c' which was the latest release until yesterday I get the error you filed.

`yarn upgrade react-scripts@2.0.0-next` which was yesterday's release I no longer get the error. Can you try this and see if it fixes it for you.

https://github.com/facebook/create-react-app/issues/5103

**Comment by lifeiscontent** [comment]
@bhough seems to work! thanks! 👍

**Comment by bhough** [comment]
@lifeiscontent great, glad it was a simple fix. Thanks for reaching out on it.
