### ISSUE TITLE
does polished support server side render ?

### ISSUE THREAD

**Issue by fattydevelop** [styled-components/polished#386]
Sorry this is not a bug report.  Here's my question.

Styled-components use babel-plugin-styled-components to support SSR.  What should I do to support SSR using polished directly 

> I'm building a components library with polished.  SSR(Server-side rendering) is very important to me and my clients.

**Comment by bhough** [comment]
@fattydevelop If the CSS-in-JS library you use supports SSR then using polished inside of it will work as well. All polished modules will render server-side similar to how normal functions inside of your CSS-in-JS do.
