### ISSUE TITLE
[Feature Request] Additional color functions

### ISSUE THREAD

**Issue by souporserious** [styled-components/polished#394]
Hello 👋,

I'd like to discuss the possibility of adding more helper functions for color if they seem like a good fit. These are all heavily inspired by the [Color](https://github.com/Qix-/color) library, as well as [Colorable](https://github.com/jxnblk/colorable) by Brent Jackson.

### getColorContrast

Follows [W3's recommended ratio](http://www.w3.org/TR/WCAG20/#contrast-ratiodef) to calculate color contrast.

```js
function getColorContrast(color1, color2) {
  const luminance1 = getLuminance(color1)
  const luminance2 = getLuminance(color2)
  return parseFloat(
    (luminance1 > luminance2
      ? (luminance1 + 0.05) / (luminance2 + 0.05)
      : (luminance2 + 0.05) / (luminance1 + 0.05)
    ).toFixed(2),
  )
}
```

### getColorContrastScores

Again, following the [contrast scores recommended by W3](https://www.w3.org/TR/WCAG20/#visual-audio-contrast).

```js
function getColorContrastScores(color1, color2) {
  const contrastRatio = getColorContrast(color1, color2)
  return {
    AA: contrastRatio >= 4.5,
    AALarge: contrastRatio >= 3,
    AAA: contrastRatio >= 7,
    AAALarge: contrastRatio >= 4.5,
  }
}
```

### isColorLight

This could be used internally in the `readableColor` function.

```js
function isColorLight(color) {
  return getLuminance(color) > 0.179
}
```

### isColorDark

```js
function isColorDark(color) {
  return !isColorLight(color)
}
```

Lastly, [here is an example](https://codesandbox.io/s/53l9qm1m8x) with them in use.

Please let me know if these sound like good additions and I'll be happy to put a PR together 🙂.

**Comment by bhough** [comment]
@souporserious We are looking to implement at least a portion of this into polished 3.4.x. (likely the first two suggestions) If you are still interested, we'd love to put a PR together.

**Comment by souporserious** [comment]
Yeah, definitely! I'll start working on a PR. Would you like them as separate PRs or is grouped ok?

**Comment by bhough** [comment]
@souporserious As a single PR is just fine.

**Comment by souporserious** [comment]
Added a PR that adds `getColorContrast` and `getColorContrastScores`. I tried to follow the code style and tests as much as possible. Please let me know if there is anything you'd like me to change and I'll get it updated. Excited to get these added! Thanks!

**Comment by briandipalma** [comment]
Sorry has `getColorContrast` been added to the library? I don't see it in the documentation

**Comment by briandipalma** [comment]
Sorry I misread it as a `getContrastingColor(color)` function
