### ISSUE TITLE
Question: How to: rem addition

### ISSUE THREAD

**Issue by donifer** [styled-components/polished#395]
- `polished` version: 2.3.3
- `JSS-in_CSS` library and version: styled-components 4.1.3
- Any relevant JS library and version: React 16

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
const small = rem(20, 16);
const big = rem(30, 16);
```
Question:
Is there a way to have the addition of `small + big` now that they are `rem`s?

I can always create a function that removes the `rem` converts to `number`, add them together and convert to string + `rem`. Wanted to know if there is a better way.

**Comment by bhough** [comment]
@donifer We're currently working on a set of math modules that will come out with 3.0.

How you're doing it now is the best way, but we do provide helpers such as https://polished.js.org/docs/#getvalueandunit and https://polished.js.org/docs/#stripunit that can aid in this.
