### ISSUE TITLE
Polished is not being tree-shaken

### ISSUE THREAD

**Issue by mikeheddes** [styled-components/polished#396]
- `polished` version: 2.3.3
- `styled-components` version: 4.1.3
- `react` version: 16.7.0
- `create-react-app` version: 2.1.1

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
import React, { Component } from "react";
import styled from "styled-components";
import { transparentize } from "polished";

const Header = styled.div`
  background-color: ${transparentize(0.5, '#ffcc00')};
`;

class App extends Component {
  render() {
    return (
      <Header>
          Learn React
      </Header>
    );
  }
}

export default App;
```

What you are seeing:

| Name                       | Size    |
|----------------------------|---------|
| polished.es.js file        | 94 KB   |
| polished.es.js bundle part | 92.6 KB |

File: 
<img width="263" alt="screenshot 2019-01-25 at 14 50 42" src="https://user-images.githubusercontent.com/26207957/51750215-ade0c580-20b1-11e9-85e6-a84c2d805466.png">

Bundle visualizer output:
![screenshot 2019-01-25 at 14 02 57](https://user-images.githubusercontent.com/26207957/51750220-b20ce300-20b1-11e9-9236-ef023a46ac7d.png)

What you expected to see:
I expect the size of just `transparentize` to be smaller.

Reproduction:
Use `create-react-app`, I ejected to add `webpack-bundle-visualizer` and install `styled-components` and `polished`. Change the app component to the one above and run `npm run build`.

**Comment by mikeheddes** [comment]
I had a lot of trouble to get tree-shaking to work on a react component library I was making for a company. I made an article to document my findings, you can read it at: https://mikeheddes.nl/articles/tree-shaking-nodejs-library. I am pretty sure the same steps will make this library tree-shakable as well. I will test it now.

**Comment by mikeheddes** [comment]
After some research I found that I was wrong. The library is already tree-shakable. I was looking at the stats size but I should be looking at the parsed size. Here are two images to show that tree-shaking is already working. The first image shows that when using the minified UMD build the parsed size is 28.26 KB and the second image shows that when using the ES6 build the parsed size is 9.36 KB which is significantly smaller.

### UMD minified build result
<img width="508" alt="screenshot 2019-01-25 at 15 44 50" src="https://user-images.githubusercontent.com/26207957/51752899-d5875c00-20b8-11e9-9416-a855726360ad.png">

### ES build result
<img width="623" alt="screenshot 2019-01-25 at 15 43 59" src="https://user-images.githubusercontent.com/26207957/51752910-d91ae300-20b8-11e9-9523-3b5c39d0c6bf.png">

Sorry for the misunderstanding, will close this now.

**Comment by bhough** [comment]
@mikeheddes thanks Mike! How this shows up in the bundle visualizer even throws me off (this changed recently ).
