### ISSUE TITLE
[Feature Request] More Triangle Directions

### ISSUE THREAD

**Issue by hbharding** [styled-components/polished#399]
Hey there!

First off, thanks for making this awesome utility! I'm wondering if it would be possible to add support for more triangle directions? Currently, `triangle` only supports `top` `bottom` `left` and `right` directions. For my use case, I'm looking for a `bottomLeft` direction, but it doesn't exist.

I've used this CSS triangle generator for past projects http://apps.eky.hk/css-triangle-generator/
It would be great if the `triangle` function could replicate these features.

<3

**Comment by bhough** [comment]
@hbharding managed to find a way to implement this and still reduce the overall size of `triangle`(#422). I would look for it to land as part of 3.2 in the coming weeks.

**Comment by bhough** [comment]
Added in 3.2.0
