### ISSUE TITLE
SyntaxError: invalid regexp group in Firefox

### ISSUE THREAD

**Issue by selrond** [styled-components/polished#400]
- `polished` version: ^3.0.0-beta.1

Mixin/Helper/Shorthand you were using and how you were using it:

```jsx
import { fluidRange } from 'polished'

const globalStyles = css`
  html {
    ${fluidRange({
      prop: 'font-size',
      fromSize: '14px',
      toSize: '18px',
    })}
  }
`
```

What you are seeing:

White screen, console error:
`SyntaxError: invalid regexp group`

Reproduction: (Works in Chrome, does not in Firefox <= 65.0)

https://codesandbox.io/s/k2no733zyo?expanddevtools=1

I believe this is because of negative lookbehind in https://github.com/styled-components/polished/blob/v3.0.0-beta.1/src/math/math.js#L5 which [is not yet supported](http://kangax.github.io/compat-table/es2016plus/#test-RegExp_Lookbehind_Assertions) in many environments

**Comment by selrond** [comment]
Let me know if there's something I can do to fix it

**Comment by bhough** [comment]
@selrond Thanks for catching this. I will give it a look tonight, but likely we will need to modify the code to replace the negative lookbehind to use a negative lookahead instead.

**Comment by bhough** [comment]
@selrond Should be good now with beta.2

https://codesandbox.io/s/8l67xqmk20

**Comment by selrond** [comment]
@bhough works, thanks!
