### ISSUE TITLE
[Feature Request] Alias timing functions with 'ease' and allow percentage based easing

### ISSUE THREAD

**Issue by markoradak** [styled-components/polished#402]
It might be good to have `easeIn()`, `easeOut()` and `easeInOut()` functions that would work pretty much the same as a `timingFunctions()`, but would allow us to write something like: `easeOut('expo')` instead of `transitionFunctions('easeOutExpo')`, since no other timing functions are available or make sense. It is quite a bit shorter, and we can leave current timing functions implementation along with it for backward compatibility.

On another point, the same function(s) could accept number as an argument, that would interpolate that number to a cubic bezier function. Therefore if we had `easeOut(0.5)` it would yield `cubic-bezier(0, 0, 0.5, 1)`.

What are your thoughts on this? 

I am happy to do a PR if you guys think it's a good idea.

**Comment by bhough** [comment]
This has been addressed in v4 which is now in beta and will be released in the coming weeks:

`npm install polished@next`
`yarn add polished@next`
