### ISSUE TITLE
[Feature Request] common easing functions

### ISSUE THREAD

**Issue by Slashgear** [styled-components/polished#404]
Hey there!

Easing functions used in transition are very limited in CSS (ease, ease-in, ease-out, ease-in-out).

A common extended list of easing function are classified here https://easings.net/
It would be very useful to have those values defined in polished.

I could do that 😉

**Comment by GrzegorzWidla** [comment]
@Slashgear I'm not sure if you're unaware of this feature already being there if I'm missing something.

`polished` exports function called `timingFunctions`. It can be used as such:

```js
import styled from 'styled-components';
import { timingFunctions } from 'polished';

const Link = styled.a`
    transition: color 300ms ${timingFunctions('easeInOutQuint')} 0ms;
`;
```

Or combined with another function, `transitions`, from `polished`:

```js
import styled from 'styled-components';
import { transitions, timingFunctions } from 'polished';

const Link = styled.a`
    ${transitions(`color 300ms ${timingFunctions('easeInOutQuint')} 0ms`};
`;
```

Is that what you're looking for or something more?
