### ISSUE TITLE
TypeScript cannot find module "polished"

### ISSUE THREAD

**Issue by Arrow7000** [styled-components/polished#410]
- `polished` version: 3.0.0
- `JSS-in_CSS` library and version: styled-components 4.1.3
- Any relevant JS library and version: React 16.8.2, TypeScript 3.3.3

I am simply trying to import a function from the module but TS can't find the module.

```typescript
import { lighten } from "polished";
```

What you are seeing:

![image](https://user-images.githubusercontent.com/13225609/53609013-daaa6000-3bbc-11e9-85fc-9162be59df59.png)

When using Parcel with TS type checking turned off my code works as expected so Parcel clearly is importing the correct code. But TS in VS Code is telling me that it can't find the module and so isn't giving me any Intellisense for `polished`.

Reproduction:

Install `polished` with `yarn add polished` and try and import it into a React TypeScript file. It says that it can't find the module.

**Comment by bhough** [comment]
@Arrow7000 I don't seem to have any issues with it:

![image](https://cdn-std.dprcdn.net/files/acc_184716/a2tMiB)

Using all the same versions you described. Here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "types": [
      "react",
      "jest",
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}```

**Comment by Arrow7000** [comment]
@bhough it looks like adding `"moduleResolution": "node"` has fixed it. I thought this was the default but I also don't really understand what it does.

Either way I think it would be a good idea to specify in the readme that this setting is required.

**Comment by bhough** [comment]
@Arrow7000 It changes what resolution algorithm TS uses when resolving imports. Oversimplification is that `classic` searches up the tree from where the file is imported while `node` mimics the Node resolution algorithm, which includes checking in `node_modules`. You can read more about it on the [TypeScript site](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

While `classic` is the default, things like CRA set it to `node` out of the box. We added a note to the README.MD in case someone runs into this again.

**Comment by Arrow7000** [comment]
Thanks @bhough!
