### ISSUE TITLE
[Feature Request] Support for base64 font src

### ISSUE THREAD

**Issue by ischyron** [styled-components/polished#416]
- `polished` version: "^2.0.3",
-  `styled-components` version: "^4.0.2",

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
fontFace({
    fileFormats: ['woff'],
    fontFamily: 'My Custom Font',
    fontFilePath: `data:application/font-woff;charset=utf-8;base64,<BASE64_STRING>',
    fontStyle: 'italic',
    fontWeight: 500,
  });
```

What you are seeing:
.woff applied to end of url() making it invalid.
and no format hint `format("woff")`
```
url("<supplied data uri>").woff
```

What you expected to see:
```CSS
@font-face {
  font-family: 'My Custom Font';
    url(data:font/truetype;charset=utf-8;base64,BASE64_ENCODED_DATA_HERE)  format("woff")`;
```
expect to see the base64 of the file inlined in url as base64.
OR 
If the consumer supply the data uri ? include it in fontface css
Also need to take into account of encoding and absolute file path if we polish does the base64 of the supplied file. 

Reproduction:

**Comment by bhough** [comment]
@ischyron This as been added to `fontFace` in [3.1.0](https://github.com/styled-components/polished/releases/tag/v3.1.0).
