### ISSUE TITLE
Get full 6-digit HEX instead of 3-digit short version

### ISSUE THREAD

**Issue by brunolemos** [styled-components/polished#420]
### Current behavior

`polished.lighten(0.95, '#242B38')` -> `'#fff'`

### Expected behavior

`polished.lighten(0.95, '#242B38')` -> `'#FFFFFF'`

or something like `toFullRgb('#fff') -> '#FFFFFF'`

or simply stop calling `reduceHexValue` internally. 

### Why

Sometimes I have issues with Android libraries that seems to only support the 6-digit version and with uppercase characters.

![image](https://user-images.githubusercontent.com/619186/54794915-b1637980-4c28-11e9-8da5-fcc3e45264f8.png)

**Comment by bhough** [comment]
@brunolemos we are unlikely to change this, unfortunately. In 99% of use cases we want the smallest possible output from color functions (which often can be a 3-digit hex). Doubling the size of the output of our color methods to serve a few Android libraries isn't something we want to do, given that this is an edge case.

We would suggest filing an issue with the library(ies) that don't support it as this is a pretty basic thing they should handle. This can also quickly be handled by a regex replace (https://stackoverflow.com/questions/10230331/how-to-convert-3-digit-html-hex-colors-to-6-digit-flex-hex-colors/10230746#10230746), so there isn't much need for us to write a custom module to convert it back.

**Comment by brunolemos** [comment]
Makes sense.

I have disabled your `reduceHexValue` function for now.
```diff
 var reduceHexValue = function reduceHexValue(value) {
+  /*
   if (value.length === 7 && value[1] === value[2] && value[3] === value[4] && value[5] === value[6]) {
     return "#" + value[1] + value[3] + value[5];
   }
+  */
 
   return value;
 };
```
