### ISSUE TITLE
[Feature Request] Helper to create sequential/staggered transitions

### ISSUE THREAD

**Issue by emattias** [styled-components/polished#423]
It would be nice to have a helper to create sequential transition string. So basically like `transitions` but it sets the delay of transitions so that they start one after another.

I'm thinking that the api might look something like:

```jsx
<div 
  style={{
    transition: sequentialTransitions(['height 1s ease-in', 'width 2s', 'opacity 1s'])
  }}
/>
```

which would be the same as writing:

```jsx
<div 
  style={{
    transition: 'height 1s ease-in, width 2s 1s, opacity 1s 3s'
  }}
/>
```

(so basically it takes care of setting the `transition-delay` property)

With this you would be able to do stuff like this with transitions (the gif drops some frames, the transition is actually smoother 😬. But the point is that it's sequential anyway 🙂):

![image](https://camo.githubusercontent.com/4933f04b056c26eb111547b4b4ca64c496f3c41f/68747470733a2f2f692e6779617a6f2e636f6d2f36646364343036383564653664313539623737363638333661363835616134632e676966)

**Comment by andyhmltn** [comment]
+1 on this request. This would be super useful

**Comment by bhough** [comment]
This feature hasn't garnered enough support to implement. We are open to revisiting the decision if demand increases.
