### ISSUE TITLE
documentation definitions

### ISSUE THREAD

**Issue by jeremy-coleman** [styled-components/polished#425]
It would be awesome if the docs had helper definitions , for instance:

```text
opacify
Increases the opacity of a color. Its range for the amount is between 0 to 1.
opacify(amount: (number | string), color: string): string
```

to..

```text
(from W3c)
Definition and Usage
The opacity property sets the opacity level for an element.

The opacity-level describes the transparency-level, where 1 is not transparent at all, 0.5 is 50% see-through, and 0 is completely transparent.

https://www.w3schools.com/cssref/css3_pr_opacity.asp

opacify
Increases the opacity of a color. Its range for the amount is between 0 to 1.
opacify(amount: (number | string), color: string): string
```

I am willing to work on it if a PR would be accepted. Initial thoughts would be to just have a 'verbose' version of the docs for noobs like me.

**Comment by bhough** [comment]
@jeremy-coleman We're always happy to have more/better documentation. We would gladly accept a PR for this.

**Comment by bhough** [comment]
Closing this specific issue. We will be offering a variety of improvements in v4's documentation.
