### ISSUE TITLE
adjustHue bug

### ISSUE THREAD

**Issue by DavidDeprost** [styled-components/polished#437]
I've recently discovered Polished, and just love how elegant it is.
However, I've run into a bug in `adjustHue`, which I reproduced in [this codepen](https://codepen.io/DavidDeprost/pen/BeoMGJ).
I really love how well-organised and accessible the Polished codebase is, so I'll try submit a PR later.

- `polished` version: 3.3.0
- `JSS-in_CSS` library and version: styled-components 4.2.0
- Any relevant JS library and version: React 16.8.6

- Mixin/Helper/Shorthand you were using and how you were using it:

  ```javascript
  adjustHue(-25, 'orange'); // ok
  adjustHue(-25, 'cyan');   // ok
  adjustHue(-25, 'red');    // bug: returns black instead of red hue
  ```

- What you are seeing:

  Due to red having a hue of 0, subtracting anything gives a negative hue value,
  which results in black.

- What you expected to see:

  I expected it to work consistently for all colors, so never returning black instead of the desired hue.
  Hue is a value in [0 to 359], so negative values should cycle through to 359 and remain positive,
  regardless of how much was subtracted.

**Comment by DavidDeprost** [comment]
@bhough Regarding the `unconfirmed bug` label:
you might've missed it in the issue, but I actually reproduced this bug in a codepen:
https://codepen.io/DavidDeprost/pen/BeoMGJ

**Comment by bhough** [comment]
@DavidDeprost we give every report that label once we see it. Just means we haven't had a chance to even look at it (including any codepens and such).

**Comment by DavidDeprost** [comment]
Ah ok, my bad. No hurry ;)
