### ISSUE TITLE
Not possible to import ES6 module directly in the browser

### ISSUE THREAD

**Issue by stereobooster** [styled-components/polished#442]
- `polished` version: 3.4.0
- `JSS-in_CSS` library and version: N/A
- Any relevant JS library and version: N/A

Mixin/Helper/Shorthand you were using and how you were using it: (in Chrome devtools)

```javascript
let polished;
import("https://unpkg.com/polished@3.4.0/dist/polished.es.js").then(m => polished = m)
```

What you are seeing:

```
polished.es.js:1 Uncaught (in promise) TypeError: Failed to resolve module specifier "@babel/runtime/helpers/esm/extends". Relative references must start with either "/", "./", or "../".
```

What you expected to see:

polished is self contained library without external dependencies, so it should be possible to load it directly in the browser.

Reproduction:

copy/paste code from above in DevTools console

**Comment by bhough** [comment]
@stereobooster Haven't gotten to look at this closely yet, but we technically have an external dependency with @babel/runtime which is likely where that error is coming from.

**Comment by stereobooster** [comment]
But do I need `@babel/runtime` in the [browser which supports ES6 modules](https://caniuse.com/#search=es6)? Which features does it use that evergreen browsers don't support?

**Comment by stereobooster** [comment]
Ok it is possible to use ES6 modules with Pika CDN

```js
let polished;
import("https://storage.googleapis.com/pika-web-packages-02/polished/3.4.0/dist-es2019/polished.min.js").then(m => polished = m)
```

Which does additional transpilation and inlines babel runtime

**Comment by wearhere** [comment]
@bhough, is the external dependency documented anywhere (along with how to satisfy?) Don't see. Making `@babel/runtime` a peer dependency might help.
