### ISSUE TITLE
Improve return type of `stripUnit`

### ISSUE THREAD

**Issue by jasnross** [styled-components/polished#451]
With the deprecation of `getValueAndUnit` I was looking at replacing it with `stripUnit`, however the return type of `stripUnit` is not as helpful as `getValueAndUnit`, as `stripUnit` always returns `any`.

```
stripUnit(value: (string | number), unitReturn: boolean): any
```

```
getValueAndUnit(value: string): [(number | string), (string | void)]
```

- `polished` version: 3.4.1
- `JSS-in_CSS` library and version: N/A
- Any relevant JS library and version: N/A

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
const [value, unit] = stripUnit("100px", true);
```

What you are seeing:

![image](https://user-images.githubusercontent.com/1895462/61010271-95a0f200-a343-11e9-9642-18220afea20a.png)

![image](https://user-images.githubusercontent.com/1895462/61010274-9df92d00-a343-11e9-8fe8-9c91129ad6fd.png)

What you expected to see:

More well-defined return types, such as those previously returned by `getValueAndUnit`.

Reproduction:

https://codesandbox.io/s/pensive-thunder-z5ijj

**Comment by bhough** [comment]
This will be addressed in v4.

**Comment by bhough** [comment]
This has been addressed in v$ which is now in beta and will be released in the coming weeks:

`npm install polished@next`
`yarn add polished@next`
