### ISSUE TITLE
Suggestion: Add more tags to improve discoverability

### ISSUE THREAD

**Issue by nurbek-ab** [styled-components/polished#468]
- `polished` version: 3.4.2
- `JSS-in_CSS` library and version: not relevant
- Any relevant JS library and version: not relevant

First of all thank you for this great library. It's really awesome and pleasure to use. 
Recently I was searching for similar library using 'color manipulation' term. There were plenty of different libraries in the results list but polished [wasn't](https://npms.io/search?q=color+manipulation) among them. So in order to gain more attraction from people that might need this great lib I suggest adding some more tags like:
`color manipulate`, `color manipulation`, `curried color manipulation`.

Currently in some search engines like npms your lib looks like this:
![polished](https://user-images.githubusercontent.com/3624386/70779271-638e3300-1dae-11ea-8797-bc8003766257.png)

**Comment by bhough** [comment]
Added in v3.4.3! Thanks for the suggestion @nurbek-ab.
