### ISSUE TITLE
rem inside between is not calculating right

### ISSUE THREAD

**Issue by dongepulango** [styled-components/polished#470]
I'm wondering if it's just me but using **rem** inside **between** is not calculating right.

`font-size: ${between(rem('34px'), rem('56px'))};`

The calculated font-size is very small. From `56px` it becomes `27px`

Am I doing this wrong?

Thanks.

**Comment by bhough** [comment]
@dongepulango Likely related to #445 (`fluidRange` wraps `between`).

**Comment by dongepulango** [comment]
using same code in V4 I get this error:
`Error: fromSize and toSize must be provided as stringified numbers with the same units as minScreen and maxScreen.`
