### ISSUE TITLE
[Feature request]: Add a getContrastingColor function?

### ISSUE THREAD

**Issue by briandipalma** [styled-components/polished#472]
- `polished` version: latest
- `JSS-in_CSS` library and version: styled-components latest

Handy function, this is our current code but it would be nice to have it in polished.

```javascript
export function getContrastingColor(color) {
  // http://www.w3.org/TR/AERT#color-contrast
  const breakdown = Color(color);
  var brightness =
    (breakdown.red() * 299 + breakdown.green() * 587 + breakdown.blue() * 114) /
    1000;

  return brightness > 125 ? "black" : "white";
}
```

**Comment by bhough** [comment]
@briandipalma I would check out [readableColor](https://polished.js.org/docs/#readablecolor), that is likely what you are looking for.
