### ISSUE TITLE
[Feature Request]: isValidColor function?

### ISSUE THREAD

**Issue by briandipalma** [styled-components/polished#473]
- `polished` version: latest
- `JSS-in_CSS` library and version: styled-components latest

Could be a handy function for theme editors especially

```javascript
export function isValidColor(rawColor) {
  try {
    Color(rawColor);
    return true;
  } catch (e) {
    return false;
  }
}
```

**Comment by ReactGirl** [comment]
`const isValidColor = (strColor: string) => {
  const s = new Option().style;
  s.color = strColor;
  return s.color !== '';
};`

**Comment by inPhoenix** [comment]
You can achieve that by:
```javascript
const isValidColor = (strColor) => {
  const s = new Option().style;
  s.color = strColor;
  return s.color !== '';
};
`

**Comment by briandipalma** [comment]
The point isn't the code, the point is to add it to this package so users don't have to have their own versions...
