### ISSUE TITLE
Typescript error (3.4.3)

### ISSUE THREAD

**Issue by ivanov-v** [styled-components/polished#475]
- `polished` version: 3.4.3
- `JSS-in_CSS` library and version: styled-components 5.0
- Any relevant JS library and version: 16.12.0

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
export const NativeInput = styled.input<{
  variant: InputVariant;
  hasAdornment: boolean;
}>`
  ${ellipsis()};
`;
```

What you are seeing:
_Type 'Styles' is not assignable to type 'string'._

![image](https://user-images.githubusercontent.com/13759065/73174142-11b02b00-4118-11ea-9158-480bb27d3a9a.png)

What you expected to see:

Types must match

**Comment by leocavalcante** [comment]
+1 here. Just updated my deps and grabbed 3.4.3, now a previously working code shouts:
```
27:5 Argument of type 'Styles' is not assignable to parameter of type 'Interpolation<ThemeProps<DefaultTheme>>'.
  Type 'Styles' is not assignable to type 'string'.
    25 | 
    26 | const GlobalStyle = createGlobalStyle`
  > 27 |   ${din}
       |     ^
    28 |   ${dinBold}
    29 |   ${dinCondensed}
    30 |   ${dinCondensedBold}

```

The code uses `fontFace` + `createGlobalStyle`

```typescript
import {createGlobalStyle} from "styled-components";
import {fontFace} from "polished";

const din = fontFace({
  fontFamily: 'Din',
  fontFilePath: '/assets/fonts/d-din-webfont',
});

const dinBold = fontFace({
  fontFamily: 'Din',
  fontFilePath: '/assets/fonts/d-din-bold-webfont',
  fontWeight: 'bold',
});

const dinCondensed = fontFace({
  fontFamily: 'Din Condensed',
  fontFilePath: '/assets/fonts/d-dincondensed-webfont',
});

const dinCondensedBold = fontFace({
  fontFamily: 'Din Condensed',
  fontFilePath: '/assets/fonts/d-dincondensed-bold-webfont',
  fontWeight: 'bold',
});

const GlobalStyle = createGlobalStyle`
  ${din}
  ${dinBold}
  ${dinCondensed}
  ${dinCondensedBold}

  body {
    margin: 0;
    background-color: #383838;
    color: white;
  }
`;

export default GlobalStyle;
```

**Comment by ivanov-v** [comment]
Maybe [this line](https://github.com/styled-components/polished/commit/5a8fd5183acbd7b11f9865790a719a7008d0b926#diff-b855b2b1da51ef2189ca3875cb7c7006R7) breaks?

**Comment by bhough** [comment]
@ivanov-v @leocavalcante Apologies, our TS test harness didn't catch this for some reason. v3.4.4 should address this, but we will await confirmation before closing.

**Comment by ivanov-v** [comment]
> @ivanov-v @leocavalcante Apologies, our TS test harness didn't catch this for some reason. v3.4.4 should address this, but we will await confirmation before closing.

Now work without errors

**Comment by leocavalcante** [comment]
> @ivanov-v @leocavalcante Apologies, our TS test harness didn't catch this for some reason. v3.4.4 should address this, but we will await confirmation before closing.

Thank you very much for the prompt fix.
