### ISSUE TITLE
Mix miscalculating alpha channel

### ISSUE THREAD

**Issue by andreasgruenh** [styled-components/polished#477]
- `polished` version: 3.4.4
- `JSS-in_CSS` library and version: none
- Any relevant JS library and version: none

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
mix(1, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0)"
mix(0.99, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.010000000000000009)"
mix(0.9, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.09999999999999998)"
mix(0.7, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.30000000000000004)"
mix(0.6, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.4)"
mix(0.4, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.6)"
mix(0.3, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "rgba(0,0,0,0.7)"
mix(0, 'rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 0)')
// "#NaNNaNNaN"
```

What you are seeing:
Calling mix is somehow miscalculating the alpha channels. In this example, we are slowly decreasing the mixingWeight, however the alpha channel is somehow increasing inversely.

What you expected to see:

When decreasing the mixingWeight from 1 to 0, the alpha channel should be scaled in this same direction (as is the color itself).

**Comment by bhough** [comment]
Thank you for submitting this @andreasgruenh. We were able to verify this and will start looking at a fix. We will also take a look at a better return value when weight is set to 0.
