### ISSUE TITLE
polished.es.js:663 stripUnit's unitReturn functionality has been marked for deprecation in polished 4.0. It's functionality has been been moved to getUnitAndValue.

### ISSUE THREAD

**Issue by zslabs** [styled-components/polished#491]
- `polished` version: 3.5.0

What you are seeing:

In the release notes of 3.5, there's a mention to the deprecation within `stripUnit`. I've noticed an odd performance regression (development and production modes) where the console is spitting out dozens (48 in this case) of deprecated messages, even though I'm only using core utilities. Should this warning be getting thrown by Polished itself? 

[This commit](https://github.com/gremlin/chaoskit/commit/9dd4a6e370dd85d8ef749fe0f1481d392fc6b615) in my library is when I first noticed the issue. I've downgraded to 3.4.4 across my projects and the performance regression is not present anymore.

Reproduction:

<img width="1168" alt="Screen Shot 2020-03-22 at 9 10 39 AM" src="https://user-images.githubusercontent.com/1018402/77250401-31e2fe80-6c1e-11ea-9bac-28db24624964.png">

**Comment by bhough** [comment]
@zslabs A few questions:

1. What do you mean when you say you are only using core utilities? 
2. Do you have this live somewhere we can look at it (either the code or the app/site)? Our website uses the entirety v3.5 and this is not happening, so it might be a code/build specific reason you are seeing this and we're not.
3. In development mode, what is the line of code that is returning this (it should only send a warning when `true` is passed as the second argument to `stripUnit` (https://github.com/styled-components/polished/blob/master/src/helpers/stripUnit.js#L34)

**Comment by bhough** [comment]
@zslabs I think we found the problem. We missed a couple modules that were using the deprecated functionality from `stripUnit`. Give 3.5.1 (https://github.com/styled-components/polished/releases/tag/v3.5.1) a try and see if it fixes it for you.

**Comment by zslabs** [comment]
👋 @bhough that did it! I appreciate you looking into this even though my issue was a bit vague. Thanks again and have a great day!
