### ISSUE TITLE
Not able to lighten a color pulled using cssVar

### ISSUE THREAD

**Issue by timknight** [styled-components/polished#493]
- `polished` version: 3.5.1
- `JSS-in_CSS` library and version: Emotion/Styled v10.0.27
- Any relevant JS library and version: twin.macro 1.0.0-alpha.7

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
&:hover {
  background-color: ${lighten(cssVar('--brand'))}
}
```

What you are seeing:
Error: Passed an incorrect argument to a color function, please pass a string representation of a color.

What you expected to see:
I'd expect that the CSS variable would be pulled in and used within the lighten function. If I remember the lighten function and just do:

```javascript
&:hover {
  background-color: ${cssVar('--brand')}
}
```

It works just fine so it doesn't seem to be an issue with actually parsing the color.

Reproduction:
The `--brand` CSS variable was defined as `red` and `rgba(255,205,100,0.72)` during this test.

**Comment by bhough** [comment]
@timknight I believe your issue is you are missing an argument in `lighten`. The first argument should be an amount you want to lighten the color, and then the color you want it to lighten.

Working example: https://codesandbox.io/s/jolly-khayyam-d593x

**Comment by timknight** [comment]
Sorry @bhough, you're right, I ended up copying a previous version of the issue where I left that off but even adding it created the same problem. That being said I think I realized where the problem might have been happening because I did get it working. In my example I was defining the CSS variable within the `index.html` template file (in CSS) as my test and that worked just fine when it came to pulling the CSS variable out using `cssVar`, but when `lighten` was introduced it couldn't parse it (even with the first argument set properly). So I removed that from the `index.html` template and just did a `setProperty` within the file I'm working on and it was good to go.

**Comment by timknight** [comment]
I started playing a little more with this so I forked the codesandbox to better highlight what's happening. You can see here that cssVar is able to pull the color value from the `styles.css` file in your example. But if you add the `lighten` function onto the example you'll get an error.

https://codesandbox.io/s/stoic-greider-bvxls

Randomly too I noticed in your working example, it seems to only work if the color is defined with a keyword (e.g. `red`), hex code (`#ff0000`), or rgb (`rgb(255,0,0)`), but if you change that to an HSL or HSLA color it doesn't seem to parse. I'm not sure if that's as designed and I'm suppose to use the hsl function to convert that but I figured I'd call it out just in case.

**Comment by bhough** [comment]
@timknight On HSL, how are you passing it to `lighten`? I was able to get both HSL/HSLA to work here: https://codesandbox.io/s/new-pine-s7dke. Am I missing something?

On `cssVar` within another function: we will need to do some more discovery here. It happens whether you include it directly or save the result into a variable. We've eliminated `styled-components` as a cause. We will update this thread once we know more.

**Comment by timknight** [comment]
Wow, okay—I think I've been "social distancing" too long, you're totally right... I wasn't putting in a valid HSL value 🙄. Sorry about that, that works just fine.

**Comment by luizwhite** [comment]
Hi!
Why cant I find somewhere that tells that using **`toString()`** solves the cssVar issue inside methods?
`background-color: ${shade(0.2, cssVar('--button-bg').toString())};`

That solved for me

**Comment by bhough** [comment]
@luizwhite Not sure what issue you're referring to. What version are you on? It currently works inside of methods without `toString`: https://codesandbox.io/s/relaxed-lalande-4tiv5

**Comment by luizwhite** [comment]
@bhough sry, I was wrong about the solution,
but it continues not working for me
I'm working with the updated versions

**Comment by luizwhite** [comment]
@bhough update comment with codesandbox
maybe im using globalstyle wrong, can you help me?

**Comment by bhough** [comment]
@luizwhite This is a current limitation because of how styled-components processes styles. At the time the method is parsed, the variables aren't available in the DOM: https://github.com/styled-components/polished/issues/493

**Comment by luizwhite** [comment]
@bhough You mean #494 ?
I tried this solution but didnt work
https://github.com/styled-components/polished/issues/494#issuecomment-720594462

I guess we have to wait then to a better solution

**Comment by luizwhite** [comment]
So, in my case a workaround will be something like this:

_myGlobalStyles.ts_
```ts
import { createGlobalStyle } from 'styled-components';

export const rootColors = {
  buttonBg: '#ff9000',
  inputBg: '#232129',
};

export default createGlobalStyle`
 :root {
   --input-bg: ${rootColors.inputBg};
   --button-bg: ${rootColors.buttonBg};
 }
}
```
