### ISSUE TITLE
cssVar is not working as expected with  styled-components createGlobalStyle

### ISSUE THREAD

**Issue by ayhid** [styled-components/polished#494]
- `polished` version: 3.5.1
- `JSS-in_CSS` library and version:  styled-components 5.0.0
- Any relevant JS library and version: React 16.12.0

Mixin/Helper/Shorthand you were using and how you were using it:

```javascript
import { createGlobalStyle, css } from 'styled-components';
import { lighten, cssVar } from 'polished';

const styling = css`
  :root {
    --light-blue: #3c8dbc;
    --black: #111;
    --link-color: ${cssVar('--light-blue')};
    --link-hover-color: ${lighten(0.15, cssVar('--link-color'))};
}`
const AdminGlobalStyles = createGlobalStyle`
 ${styling};
`;

export default AdminGlobalStyles;
```

What you are seeing:

```
construct.js:30 Uncaught Error: CSS variable not found.

    at cssVar (polished.es.js:548)
    at Module../startup/client/AdminGlobalStyles.js (AdminGlobalStyles.js:4)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../.storybook/preview.js (generated-entry.js:5)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.0 (styles.js:3)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
```
What you expected to see:

I excpected the variable to be interpreted in the lighten function

Reproduction:
https://codesandbox.io/s/affectionate-tesla-c63ds

**Comment by bhough** [comment]
@ayhid We can look at this closer, but at first blush, this seems expected based on how `cssVar` gets access to variables. I'm assuming the error is actually on `--link-color` and it is likely due to the way styled-components parses that block. 

@probablyup can hopefully confirm, but the entire `:root` block likely gets written at once in your example so `--light-blue` is not actually in the document yet for `cssVar` to access. He might have suggestions for workarounds if that turns out to be the case.

Looks like your reproduction link is incorrect (just getting the base sandbox), if you can fix that we can poke around a bit more.

**Comment by ayhid** [comment]
@bhough Thank you for the quick reply.

I updated the reproduction link you can see the right one now.

> can hopefully confirm, but the entire :root block likely gets written at once in your example so --light-blue is not actually in the document yet for cssVar to access. He might have suggestions for workarounds if that turns out to be the case

That was my first thought too, I surely can repeat color codes in my global styles as a workaround for now. It will be great if this could work though.

Thanks again for all the great work

**Comment by ayhid** [comment]
after some debugging
I see that in the cssVar function  the getComputedStyle does not find the propertyValue relative to my css variable hope this helps
```
 if (document.documentElement !== null) {
    variableValue = getComputedStyle(document.documentElement).getPropertyValue(cssVariable);
  }
```

**Comment by bhough** [comment]
@ayhid Yep, that supports the hypothesis that the entire block is getting written at once, and therefore it is not getting written before `cssVar` is called.

**Comment by ayhid** [comment]
any idea on how to get around this except rewriting my css vars values ?

**Comment by bhough** [comment]
In general, the css-in-js community usually steers folks to using pure JS variables and theming for this type of things unless there is a clear reason it needs to be done with css variables (like inheriting an external theme you don't control).

**Comment by ayhid** [comment]
@bhough thanks a lot I'll migrate this to theme properties so.
I think this should be mentioned in the documentation maybe it will avoid others waisting some time trying to make it work

**Comment by marioolofo** [comment]
Hey guys, I'm working on a project with styled-components and polished and when I come across this bug, I found a workaround:

`const cssVar = (name: string) => {
	const el = getComputedStyle(document.documentElement);
	let v = el.getPropertyValue(name);
	if(!v) {
		v = el[name as any];
	}
	return v.trim();
};
`

The problem is, getPropertyValue don't find the variable, but lookup directly in the element works.

**Comment by hassanazimi** [comment]
@marioolofo where did you add this code?

**Comment by marioolofo** [comment]
> @marioolofo where did you add this code?

I replaced the places I use cssVar for this code, but I think that this is not really the fix, because the easy way to fix this problem is to wait for the component to mount before calling cssVar(), ex:

```
import { createGlobalStyle, css } from 'styled-components';
import { lighten, cssVar } from 'polished';

const styling = css`
  :root {
    --light-blue: #3c8dbc;
    --black: #111;
    --link-color: ${() => cssVar('--light-blue')};
    --link-hover-color: ${() => lighten(0.15, cssVar('--link-color'))};
}`
const AdminGlobalStyles = createGlobalStyle`
 ${styling};
`;

export default AdminGlobalStyles;
```

This way the cssVar() is called after the component is on DOM and the cssVar works.

**Comment by luizwhite** [comment]
Hello

In my case a workaround will be something like this:

_myGlobalStyles.ts_
```ts
import { createGlobalStyle } from 'styled-components';

export const rootColors = {
  buttonBg: '#ff9000',
  inputBg: '#232129',
};

export default createGlobalStyle`
 :root {
   --input-bg: ${rootColors.inputBg};
   --button-bg: ${rootColors.buttonBg};
 }
}
```

But I dont know, maybe there are better solutions.
Actually, with this approach, i dont know if I need css3 variables anyway
