### ISSUE TITLE
Support for Babel Macros?

### ISSUE THREAD

**Issue by FezVrasta** [styled-components/polished#495]
I think it'd be great if Polished supported Babel Macros, I see there's already a babel plugin, but for Create React App consumers that's not a viable option, and it requires additional configuration.

With babel macros support we could have:

```js
import { clearFix } from 'polished/macro';

let value = clearFix();
```

```js
let value = {
  '&::after': {
    clear: 'both',
    content: '',
    display: 'table'
  }
};
```

**Comment by bhough** [comment]
@FezVrasta We have this in our v4 Roadmap: https://github.com/styled-components/polished/issues/397
