### ISSUE TITLE
Tree Shaking is not working

### ISSUE THREAD

**Issue by avin-kavish** [styled-components/polished#499]
What you are seeing:

https://bundlephobia.com/result?p=polished@3.5.1

What you expected to see:

All individual exports are displayed as having the total size in the export analysis section. But I expected individual packages to be much smaller.

**Comment by bhough** [comment]
Please follow: https://github.com/styled-components/polished/issues/478

**Comment by avin-kavish** [comment]
@bhough Followed. But I don't see a solution
