### ISSUE TITLE
Generated Documentation

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#5]
Since complete documentation will be important, what are thoughts on using something like [JSDOC](http://usejsdoc.org) to generate docs for us?

**Comment by mxstbr** [comment]
Sounds very good to me. Let's automate as much of this lib as possible!

**Comment by ericclemmons** [comment]
We've had this discussion today @ work and went with https://github.com/documentationjs/documentation, due to it's Flow & Babel support.

**Comment by bhough** [comment]
Addressed by https://github.com/styled-components/polished/pull/15

**Comment by bhough** [comment]
Addressed by https://github.com/styled-components/polished/pull/15
