### ISSUE TITLE
pkg.jsnext:main

### ISSUE THREAD

**Issue by klarstrup** [styled-components/polished#502]
- `polished` version: 3.6.0

The addition of this property in package.json led to some ES2015+ code slipping into my bundle and breaking IE11 support, I can easily alias to the CJS build but I think you might like to know that:

A. You've put a breaking change in a minor version bump

B. There are assumptions in the ecosystem that `jsnext:main` contains an es5-ified build

C. `jsnext:main` is deprecated per, like, 2017 and I think you're generally better off not specifying it, I couldn't find any reason this was added to this project in the first place within the PR that it was.

**Comment by bhough** [comment]
@klarstrup Thanks for catching this. We still support this field in styled-components and it got copied over improperly. 3.6.1 should now properly only have the CJS and ESM builds.
