### ISSUE TITLE
Proper way to build es5 bundle files

### ISSUE THREAD

**Issue by koba04** [styled-components/polished#504]
## Question

At 3.6.0, `polished` has added a `module` field and put a file for browsers that support ES Modules. It is great for developers who build a bundle file to be used with `script type="module"`.
However, the change would break many applications on IE11 because `webpack` uses the `module` field in `pacakge.json` automatically if it exists.

I think it makes sense to put a file for browsers that support ES Modules into the `module` field, but it seems not to be an ecosystem compatible, and 
many developers don't adopt "module/no module pattern" yet, so it would be nice if `polished` provides an option for the use-case, makes the file ES5 compatible, or adds a note into `README.md`.
For example, `redux` and `react-router` have a `module` field in its `package.json`, but the file is an ES5 compatible.

What is the best way to use `polished` in an ES5 compatible build file that is enabled Tree-Shaking?

## Relevant Information

I've found a similar discussion for the issue.
https://github.com/styled-components/polished/issues/502

**Comment by iiroj** [comment]
We were able to work around this issue by forcing webpack's babel-loader to transform `polished`. We use something like this to easily add packages from node_modules:

```js
// Dependencies that should be transpiled with Babel
const transpileDependencies = ['polished']

module.exports = {
module: {
    rules: [
        {
            test: /\.(js|jsx)$/,
            exclude: new RegExp(`node_modules/(?!(${transpileDependencies.join('|')})/).*`),
            use: [
                {
                    loader: 'babel-loader',
                }
            ]
        }
}
```

What this does is generate an RegExp that excludes everything under node_modules _but_ the dependencies listed in `transpileDependencies`.

**Comment by bhough** [comment]
@koba04 This was due to us adding `esmodules: true` to the babel/preset-env config when building the `esm` bundle. We've always offered a es5, tree-shaking compatible bundle in the `module` field, but this setting caused babel to ignore our browser targets and thus break compatibility.

If you pull v.3.6.2 this should address your issue.

**Comment by koba04** [comment]
@bhough Amazing!😍 Thank you for your fix!
