### ISSUE TITLE
`rgbToColorString` produces wrong color when `alpha` is `0`

### ISSUE THREAD

**Issue by sgoll** [styled-components/polished#515]
- `polished` version: 3.6.3

## Mixin/Helper/Shorthand Usage

```javascript
rgbToColorString({ red: 255, green: 205, blue: 100, alpha: 0.0 })
```

## What You Are Seeing

The (wrong) result is `#ffcd64`.

## What You Expected To See

The expected result is `rgba(255,205,100,0)`.

## Reproduction

https://codesandbox.io/s/patient-lake-tdqty

## Analysis

The problem is this comparison:

https://github.com/styled-components/polished/blob/faac33f7a68874eed95701c208ae78e412dc1af9/src/color/rgbToColorString.js#L39

The evaluation of `color.alpha` is probably not necessary at all. Any not-null (`null`/`undefined`) checks are included in `typeof color.alpha === 'number'` already.

**Comment by bhough** [comment]
Thank you for filing the issue @sgoll. v3.6.4 addresses this issue.
