### ISSUE TITLE
Correct use of `normalize` with object styles

### ISSUE THREAD

**Issue by alexbrt** [styled-components/polished#544]
## Question
Hi :wave:, commit 5c684e6d4d888189405b88571a29812f646fd9af changed the `normalize` mixin to return a 2-object array of styles. Currently, it's compatible with `emotionjs` and `styled-components` template literals but doesn't seem to work with object styles unless used as follows:  
```js
const styles = { ...normalize()[0] };
```
Is this the intended use of `normalize` with object styles?

**Comment by bhough** [comment]
@alexbrt The reason for that change was to properly handle the fallback needed for `'abbr[title]'`'s `textDecoration` property. To make the current implementation work with object notation you will need to get creative depending on the library you are using. For example, the following should work with `emotion` and `jss`: https://cssinjs.org/jss-syntax/?v=v10.4.0#fallbacks

```javascript
const styles = {
  ...normalize()[0],
  "abbr[title]": {
    textDecoration: [
      normalize()[0]["abbr[title]"]["textDecoration"],
      normalize()[1]["abbr[title]"]["textDecoration"]
    ]
  }
};
```

Unfortunately, object notation fallbacks don't work the same way in styled-components: https://github.com/styled-components/styled-components/issues/3135 or React itself: https://github.com/facebook/react/issues/2020. Without extra processing, the fallback will just git overwritten. The way you are currently doing it will ignore the value provided in the second array and always use the fallback value. This is probably safe as it really is the one property and the difference between the "preferred" value and the fallback is minimal.

**Comment by alexbrt** [comment]
Got it, thanks! :+1:
