### ISSUE TITLE
Version 4 major changes?

### ISSUE THREAD

**Issue by sever1an** [styled-components/polished#545]
## Question

What are the major changes between version 3 and version 4? Do I need to change any code before upgrading? Is there anything we need to be aware of?

**Comment by bhough** [comment]
Release notes can be found here: https://github.com/styled-components/polished/releases

**Comment by sever1an** [comment]
I looked around the website and docs but couldn't find it, now I'm a bit embarrassed for creating an issue. Thanks for the help!

**Comment by bhough** [comment]
@sever1an No reason to be! Our site is getting a major overhaul so we can make things like this easier to find.
