### ISSUE TITLE
transparentize - float numbers to 2 decimals

### ISSUE THREAD

**Issue by sandrina-p** [styled-components/polished#548]
- `polished` version: 4.0.2

## Mixin/Helper/Shorthand Usage

```javascript
// It happens with any color actually
transparentize(0.55, '#01B0BB') // rgba(1,176,187,0.44999999999999996)
```

## What You Are Seeing

The output is `rgba(1,176,187,0.44999999999999996)`
## What You Expected To See

The output to be `rgba(1,176,187,0.45)`

## Reproduction

https://codesandbox.io/s/polished-transparentize-055-bug-dm3o7

**Comment by bhough** [comment]
@sandrina-p This has been addressed in v4.0.4.
