### ISSUE TITLE
Lighten seems to go from 0 - 0.2 is the maths broken ?

### ISSUE THREAD

**Issue by leojauncey** [styled-components/polished#580]
- `polished` version: v4.1.2

## What You Are Seeing

lighten seems to return white for any value over 0.2

## What You Expected To See

lighten amount from 0 to 1

**Comment by aleksandrlat** [comment]
@leojauncey it depends on current color lightness.

Color is converted to HSL format in `lighten` function https://github.com/styled-components/polished/blob/main/src/color/lighten.js#L32

When color is converted to HSL it already has some lightness. 

Please refer to https://en.wikipedia.org/wiki/HSL_and_HSV

Maybe just `setLightness` instead
