### ISSUE TITLE
[Possible improvements] I found some places I could improve performance and Bundle size

### ISSUE THREAD

**Issue by thadeucity** [styled-components/polished#622]
## Question
Hello, I'm a **polished** user, and it was always super useful for me, thank you guys for the lib.

Reading the code today I found some places I could help by reducing the bundle size, or by making some minor performance improvements, and I want to know if I can help with the project and open a pull request for this.
 
### Examples: 
- The `toColorString` function checks if an object matches a series of expected keys, since this validation follows the same behavior every time it can be altered to a generic function that receive the keys that need validation. (A 15% reduction in file size)

- The `tint` and `shade` functions passes `rgb(255, 255, 255)` to the `mix` function, that passes it to the `parseToRgb` function, inside it the string is normalized and checked to be parsed, since the first checking function expects a hex color, using a hex color like `#FFFFFF` on these two functions would avoid 4 regex matches and 4 ifs for each one.

- I'm still reading all the code but I'm having some other ideas for other parts of the code. Please let me know if I can help

**Comment by bhough** [comment]
@thadeucity Definitely open to improvements and contributions. Some of this is on our 5.0 list, which we've admittedly been very slow to work through.
