### ISSUE TITLE
Jest tests stall constantly on Travis

### ISSUE THREAD

**Issue by bhough** [styled-components/polished#69]
Over the last couple of weeks the Jest tests have been practically unusable on Travis. 9 times out of 10 them time out. When they do successfully run they take 8-10 minutes to complete. This is making submitting PRs a huge pain.

**Comment by mxstbr** [comment]
Any ideas what's up with that?

**Comment by nikgraf** [comment]
@bhough just noticed the same, no idea why …

**Comment by nikgraf** [comment]
@bhough I switched to Yarn and did some cleanup which resulted in a way faster build time (2min): https://travis-ci.org/styled-components/polished/builds/192093050

Kind of strange though …

**Comment by bhough** [comment]
@mxstbr I'm ok with this, but I know initially you had discussed not using requiring use of yarn to make it more new developer friendly. Is that still the case?

**Comment by mxstbr** [comment]
This is solely on CI so it runs faster, no contributors have to use yarn I don't think?

**Comment by bhough** [comment]
yeah I guess as long as running the tests through npm work locally, it is ok. Though I'd really like to understand why one works on travis and the other doesn't. They are both ultimately aliasing to `jest src`. Strange that switching to yarn would somehow fix that.
