### ISSUE TITLE
Flow type references missing in docs

### ISSUE THREAD

**Issue by diegohaz** [styled-components/polished#71]
Hi, guys,

I see some flow type references missing in docs like this `RgbaColor`.

![image](https://cloud.githubusercontent.com/assets/3068563/21960718/79cb2c90-dadb-11e6-8632-fe817b304ae3.png)

I'm playing with `Flow` and `Documentation` on another project and also faced this problem, but I finally managed to solve it.

Would a PR be welcome?

**Comment by nikgraf** [comment]
absolutely! yes please

**Comment by mxstbr** [comment]
Whoa I would love to solve this! Awesome!!
