### ISSUE TITLE
Issue with react-boilerplate & retinaImage

### ISSUE THREAD

**Issue by thillin** [styled-components/polished#82]
Hi there,

I'm trying to use retinaImage in react-boilerplate to render hi resolution copies of images throughout my project on high resolution screens. I've manually included retinaImage.js and hiDPI.js in my project, imported retinaImage.js into the appropriate component and attempted to use it with a static string and am hitting the following error:

```JSON
Dynamic page loading failed TypeError: Cannot read property '0' of undefined
at SafeParser.decl (styled-components.es.js:2298)
    at SafeParser.precheckMissedSemicolon (styled-components.es.js:5087)
    at SafeParser.decl (styled-components.es.js:2331)
    at SafeParser.other (styled-components.es.js:2228)
    at SafeParser.loop (styled-components.es.js:2171)
    at safeParse (styled-components.es.js:5114)
    at ComponentStyle.generateAndInjectStyles (styled-components.es.js:7158)
    at StyledComponent.generateAndInjectStyles (styled-components.es.js:6219)
    at eval (styled-components.es.js:6239)
    at subscribe (styled-components.es.js:6073)
```

for context, here's the relevant parts of the component:

```javascript
import retinaImage from '../../lib/retinaImage'

const PersonImage = styled.img`
  height: 360px;
  width: 555px;
  background-image: ${retinaImage('https://retinajs.s3.amazonaws.com/images/backgrounds/bg.jpg')};
  background-size: cover;
  background-position: center;
`
```

I was wondering if this is possibly something to do with the image minification that takes place in react-boilterplate?

Please let me know if you need any more information and apologies if it's simply me misunderstanding something or if there's somewhere more appropriate to ask this.

Thanks for all the work on styled-components/react-boilerplate etc. they're making my latest project worlds more enjoyable to write!

**Comment by bhough** [comment]
@thillin not super familiar with boiler plate, but can try to help. The first thing I notice is that you are providing a file extension. Try removing that and let me know if that works. We can probably make this a bit more robust to automatically read an extension if it is passed.

**Comment by thillin** [comment]
Hi @bhough - sorry for the late response! 

I've given that a go and am getting an identical error, honestly I didn't even realise that a file extension wasn't expected.

Just for reference, this is what I'm trying at the moment. I also had a look over the weekend and it appears the error is occurring in styled-components/vendor/postcss if that's of any use.

```javascript

const ArtistsImage = styled.img`
  height: 360px;
  width: 555px;
  background-image: ${retinaImage('https://retinajs.s3.amazonaws.com/images/backgrounds/bg')}; 
  background-size: cover;
  background-position: center;
`
```

**Comment by bhough** [comment]
@mxstbr could the issue here be that post css doesn't support nested media queries?

**Comment by bhough** [comment]
@thillin it should look like:

```javascript
const ArtistsImage = styled.img`
  height: 360px;
  width: 555px;
  ${retinaImage('https://retinajs.s3.amazonaws.com/images/backgrounds/bg')}; 
  background-size: cover;
  background-position: center;
`
```

you are trying to set it's return value to a property, when it already contains the property and the values in the return: https://github.com/styled-components/polished/blob/master/src/mixins/retinaImage.js#L10

**Comment by thillin** [comment]
@bhough 😓 My bad. Thanks for the input though, much appreciated!

I do think support for when an extension is included in a string would be a useful feature though.

**Comment by bhough** [comment]
no problem at all @thillin. That is what we are here for.
