### ISSUE TITLE
Improvements (Chores)

### ISSUE THREAD

**Issue by nikgraf** [styled-components/polished#91]
I'm going to use this a personal todo list until the initial release. Some of these are for discussion. I just don't want to forget any of these.

- [x] make sure the color types are exposed
- [x] move color related functions to a color directory
- [x] accept rgba strings with spaces (right now it expects strings without spaces). Perquisite: need to check if one ore more spaces are allowed
- [x] accept other color strings as well (hsl, rgb, hsla)
- [x] decide if we use our functions in the inline examples
- [x] investigate ES2015 build for Treeshaking optimizations
- [x] turn on linting for tests
- [ ] add a warning for the order of arguments
- [x] investigate how compose works under the hood (Nik currently working on it)
- [ ] interactive examples in the docs (bonus chore) :)
- [ ] document color usage somewhere + write a post about the api design
- [ ] check how to properly type check in `toColorString`
- [ ] replace toColorString usage with hslToColorString & rgbToColorString (perf)
- [x] export flow types

**Comment by bhough** [comment]
@nikgraf on the treeshaking front, from what I can see from the rollup docs the change @mxstbr made in #98 we should be pretty close to using native modules for treeshaking.

**Comment by bhough** [comment]
@nikgraf regarding:

> accept rgba strings with spaces (right now it expects strings without spaces). Perquisite: need to check if one ore more spaces are allowed

Where in the string are you referring to allowing spaces?

**Comment by nikgraf** [comment]
@bhough https://github.com/styled-components/polished/blob/master/src/color/parseToRgb.js#L8-L11

**Comment by 10xjs** [comment]
@nikgraf I can look into the `rgba` whitespace question

**Comment by nikgraf** [comment]
@10xjs that would be awesome

**Comment by krainboltgreene** [comment]
Is there a plan to support all CSS properties as functions?

**Comment by bhough** [comment]
@krainboltgreene can you give an example of one you want to see as a function?

**Comment by krainboltgreene** [comment]
@bhough Grid, flexbox, basically anything that can be expanded into multiple computed properties from a single shorthand.

**Comment by bhough** [comment]
@krainboltgreene I'd be curious what an api for that would look like. What order would the properties be in, which ones could you skip, what would (if any) the defaults be? 

We are very hesitant to create concepts that don't follow somewhat closely to what is already in CSS. The closest we've gotten is with things like `border-radius`, but we are still following the clockwise rotation. 

Also for the two examples you've given, there would possibly need to be a shorthand for both parent and children. Not 100% against it, but I'd need to see a proposal that solves those issues in a way that would be friendly to the dev, and they wouldn't have to memorize our own custom ordering. Even with CSS properties that use native shorthand, the ordering can be confusing to devs. See #126

**Comment by krainboltgreene** [comment]
Noted, thanks!

**Comment by bhough** [comment]
@nikgraf Finally got around to building a little sandbox to test tree-shaking and we are all good with our current config: 

![screen shot on 2017-05-06 at 00-34-48](https://cloud.githubusercontent.com/assets/769339/25766643/edb217ee-31f3-11e7-9059-75d70410a0f5.png)

**Comment by bhough** [comment]
Closing this in favor of #176 #173 & #4
